export type LanguageCode = "fa-AF" | "ps-AF" | "en";

export const languages = [
  { code: "fa-AF", nativeName: "دری", rtl: true },
  { code: "ps-AF", nativeName: "پښتو", rtl: true },
  { code: "en", nativeName: "English", rtl: false },
] as const satisfies ReadonlyArray<{ code: LanguageCode; nativeName: string; rtl: boolean }>;

export const defaultLanguage: LanguageCode = "fa-AF";

const en = {
  "common.appName": "LeagueKick",
  "common.loading": "Loading…",
  "common.retry": "Try again",
  "common.save": "Save",
  "common.signOut": "Sign out",
  "common.online": "Online",
  "network.offlineTitle": "You are offline",
  "network.offlineBody": "Your current information stays visible. Actions that need the server will resume when you reconnect.",
  "network.backOnline": "Back online",
  "auth.welcomeBack": "Welcome back",
  "auth.loginSubtitle": "Sign in to manage your futsal activity.",
  "auth.identifier": "Phone or username",
  "auth.password": "Password",
  "auth.login": "Sign in",
  "auth.noAccount": "Don't have an account?",
  "auth.createAccount": "Create account",
  "auth.registerTitle": "Create your LeagueKick account",
  "auth.registerSubtitle": "Choose a player or venue-owner account. A venue and Premium trial are configured later.",
  "auth.displayName": "Full name",
  "auth.phone": "Phone number",
  "auth.phoneHint": "Example: 0791234567 or +93791234567",
  "auth.usernameOptional": "Username (optional)",
  "auth.accountType": "Account type",
  "auth.player": "Player",
  "auth.venueOwner": "Venue owner",
  "auth.passwordHint": "At least 10 characters",
  "auth.register": "Create account",
  "auth.haveAccount": "Already have an account?",
  "auth.invalidCredentials": "The phone/username or password is incorrect.",
  "auth.duplicateIdentity": "That phone number or username is already in use.",
  "auth.genericError": "We couldn't complete that request. Please try again.",
  "home.title": "Home",
  "home.greeting": "Hello, {name}",
  "home.foundationTitle": "Your LeagueKick account is ready",
  "home.foundationBody": "Language, secure session, role, and connectivity foundations are active.",
  "home.accountRole": "Account role",
  "home.connection": "Connection",
  "home.language": "Language",
  "home.nextTitle": "Next product milestone",
  "home.nextBody": "Venue-owner onboarding, one-venue enforcement, and the 72-hour Premium trial are implemented in Phase 2.",
  "settings.title": "Settings",
  "settings.language": "Language",
  "settings.account": "Account",
  "settings.security": "Security",
  "settings.sessionProtected": "Your refresh session is stored securely on this device.",
  "validation.required": "This field is required.",
  "validation.password": "Use at least 10 characters.",
  "validation.phone": "Enter a valid Afghanistan phone number.",
  "validation.displayName": "Enter at least 2 characters.",
  "role.PLAYER": "Player",
  "role.TEAM_MANAGER": "Team manager",
  "role.REFEREE": "Referee",
  "role.VENUE_STAFF": "Venue staff",
  "role.COMPETITION_ADMIN": "Competition admin",
  "role.VENUE_OWNER": "Venue owner",
  "role.PLATFORM_ADMIN": "Platform admin"
} as const;

export type TranslationKey = keyof typeof en;

const fa = {
  "common.appName": "لیگ‌کیک",
  "common.loading": "در حال بارگذاری…",
  "common.retry": "دوباره تلاش کنید",
  "common.save": "ذخیره",
  "common.signOut": "خروج",
  "common.online": "آنلاین",
  "network.offlineTitle": "به اینترنت وصل نیستید",
  "network.offlineBody": "اطلاعات فعلی شما باقی می‌ماند. کارهایی که به سرور نیاز دارند پس از وصل‌شدن دوباره ادامه می‌یابند.",
  "network.backOnline": "دوباره آنلاین شدید",
  "auth.welcomeBack": "خوش آمدید",
  "auth.loginSubtitle": "برای مدیریت فعالیت فوتسال خود وارد شوید.",
  "auth.identifier": "شماره تلفن یا نام کاربری",
  "auth.password": "رمز عبور",
  "auth.login": "ورود",
  "auth.noAccount": "حساب ندارید؟",
  "auth.createAccount": "ایجاد حساب",
  "auth.registerTitle": "حساب لیگ‌کیک خود را بسازید",
  "auth.registerSubtitle": "حساب بازیکن یا مالک سالن را انتخاب کنید. سالن و دوره آزمایشی پریمیوم بعداً تنظیم می‌شود.",
  "auth.displayName": "نام کامل",
  "auth.phone": "شماره تلفن",
  "auth.phoneHint": "نمونه: 0791234567 یا +93791234567",
  "auth.usernameOptional": "نام کاربری (اختیاری)",
  "auth.accountType": "نوع حساب",
  "auth.player": "بازیکن",
  "auth.venueOwner": "مالک سالن",
  "auth.passwordHint": "حداقل ۱۰ نویسه",
  "auth.register": "ایجاد حساب",
  "auth.haveAccount": "از قبل حساب دارید؟",
  "auth.invalidCredentials": "شماره/نام کاربری یا رمز عبور نادرست است.",
  "auth.duplicateIdentity": "این شماره تلفن یا نام کاربری قبلاً استفاده شده است.",
  "auth.genericError": "درخواست تکمیل نشد. لطفاً دوباره تلاش کنید.",
  "home.title": "خانه",
  "home.greeting": "سلام، {name}",
  "home.foundationTitle": "حساب لیگ‌کیک شما آماده است",
  "home.foundationBody": "زبان، نشست امن، نقش کاربری و وضعیت اتصال فعال است.",
  "home.accountRole": "نقش حساب",
  "home.connection": "اتصال",
  "home.language": "زبان",
  "home.nextTitle": "مرحله بعدی محصول",
  "home.nextBody": "ثبت سالن مالک، محدودیت یک سالن و دوره آزمایشی ۷۲ ساعته پریمیوم در فاز ۲ پیاده‌سازی می‌شود.",
  "settings.title": "تنظیمات",
  "settings.language": "زبان",
  "settings.account": "حساب",
  "settings.security": "امنیت",
  "settings.sessionProtected": "نشست تازه‌سازی شما به‌صورت امن در این دستگاه نگهداری می‌شود.",
  "validation.required": "این بخش الزامی است.",
  "validation.password": "حداقل ۱۰ نویسه استفاده کنید.",
  "validation.phone": "یک شماره معتبر افغانستان وارد کنید.",
  "validation.displayName": "حداقل ۲ نویسه وارد کنید.",
  "role.PLAYER": "بازیکن",
  "role.TEAM_MANAGER": "مدیر تیم",
  "role.REFEREE": "داور",
  "role.VENUE_STAFF": "کارمند سالن",
  "role.COMPETITION_ADMIN": "مدیر رقابت",
  "role.VENUE_OWNER": "مالک سالن",
  "role.PLATFORM_ADMIN": "مدیر پلتفرم"
} satisfies Record<TranslationKey, string>;

const ps = {
  "common.appName": "لیګ‌کېک",
  "common.loading": "در حال بارولو…",
  "common.retry": "بیا هڅه وکړئ",
  "common.save": "خوندي کول",
  "common.signOut": "وتل",
  "common.online": "آنلاین",
  "network.offlineTitle": "تاسو انټرنېټ سره نه یاست نښتي",
  "network.offlineBody": "ستاسو اوسني معلومات پاتې کېږي. هغه کارونه چې سرور ته اړتیا لري د بیا نښلېدو وروسته دوام کوي.",
  "network.backOnline": "بیا آنلاین شوئ",
  "auth.welcomeBack": "ښه راغلاست",
  "auth.loginSubtitle": "د خپل فوتسال فعالیت د مدیریت لپاره ننوځئ.",
  "auth.identifier": "د تلیفون شمېره یا کارن‌نوم",
  "auth.password": "پټنوم",
  "auth.login": "ننوتل",
  "auth.noAccount": "حساب نه لرئ؟",
  "auth.createAccount": "حساب جوړول",
  "auth.registerTitle": "خپل لیګ‌کېک حساب جوړ کړئ",
  "auth.registerSubtitle": "د لوبغاړي یا د میدان د مالک حساب وټاکئ. میدان او Premium آزمایښتي موده وروسته تنظیمېږي.",
  "auth.displayName": "بشپړ نوم",
  "auth.phone": "د تلیفون شمېره",
  "auth.phoneHint": "بېلګه: 0791234567 یا +93791234567",
  "auth.usernameOptional": "کارن‌نوم (اختیاري)",
  "auth.accountType": "د حساب ډول",
  "auth.player": "لوبغاړی",
  "auth.venueOwner": "د میدان مالک",
  "auth.passwordHint": "لږ تر لږه ۱۰ توري",
  "auth.register": "حساب جوړول",
  "auth.haveAccount": "له مخکې حساب لرئ؟",
  "auth.invalidCredentials": "د تلیفون/کارن‌نوم یا پټنوم ناسم دی.",
  "auth.duplicateIdentity": "دا د تلیفون شمېره یا کارن‌نوم له مخکې کارول شوی.",
  "auth.genericError": "غوښتنه بشپړه نه شوه. بیا هڅه وکړئ.",
  "home.title": "کور",
  "home.greeting": "سلام، {name}",
  "home.foundationTitle": "ستاسو لیګ‌کېک حساب چمتو دی",
  "home.foundationBody": "ژبه، خوندي ناسته، رول او د اتصال بنسټ فعال دی.",
  "home.accountRole": "د حساب رول",
  "home.connection": "اتصال",
  "home.language": "ژبه",
  "home.nextTitle": "بل محصول پړاو",
  "home.nextBody": "د میدان د مالک ثبت، د یوه میدان محدودیت او د Premium ۷۲ ساعته آزمایښتي موده په ۲ پړاو کې پلي کېږي.",
  "settings.title": "تنظیمات",
  "settings.language": "ژبه",
  "settings.account": "حساب",
  "settings.security": "امنیت",
  "settings.sessionProtected": "ستاسو د ناستې د نوي کولو معلومات په دې وسیله کې خوندي ساتل کېږي.",
  "validation.required": "دا برخه اړینه ده.",
  "validation.password": "لږ تر لږه ۱۰ توري وکاروئ.",
  "validation.phone": "د افغانستان معتبره شمېره ولیکئ.",
  "validation.displayName": "لږ تر لږه ۲ توري ولیکئ.",
  "role.PLAYER": "لوبغاړی",
  "role.TEAM_MANAGER": "د ټیم مدیر",
  "role.REFEREE": "ریفري",
  "role.VENUE_STAFF": "د میدان کارکوونکی",
  "role.COMPETITION_ADMIN": "د سیالۍ مدیر",
  "role.VENUE_OWNER": "د میدان مالک",
  "role.PLATFORM_ADMIN": "د پلاتفورم مدیر"
} satisfies Record<TranslationKey, string>;

const resources: Record<LanguageCode, Record<TranslationKey, string>> = { "fa-AF": fa, "ps-AF": ps, en };

export function isRtlLanguage(language: LanguageCode): boolean {
  return language === "fa-AF" || language === "ps-AF";
}

export function translate(language: LanguageCode, key: TranslationKey, params?: Record<string, string | number>): string {
  let value: string = resources[language][key] ?? en[key];
  if (!params) return value;
  for (const [name, replacement] of Object.entries(params)) {
    value = value.replaceAll(`{${name}}`, String(replacement));
  }
  return value;
}

export function getLanguage(language: LanguageCode) {
  return languages.find((item) => item.code === language) ?? languages[0];
}
