export type LanguageCode = "fa-AF" | "ps-AF" | "en";

export const languages = [
  { code: "fa-AF", nativeName: "دری", rtl: true },
  { code: "ps-AF", nativeName: "پښتو", rtl: true },
  { code: "en", nativeName: "English", rtl: false },
] as const satisfies ReadonlyArray<{ code: LanguageCode; nativeName: string; rtl: boolean }>;

export const defaultLanguage: LanguageCode = "fa-AF";

const en = {
  "common.appName": "LeagueKick",
  "common.loading": "Loading…",
  "common.retry": "Try again",
  "common.save": "Save",
  "common.signOut": "Sign out",
  "common.online": "Online",
  "network.offlineTitle": "You are offline",
  "network.offlineBody": "Your current information stays visible. Actions that need the server will resume when you reconnect.",
  "network.backOnline": "Back online",
  "auth.welcomeBack": "Welcome back",
  "auth.loginSubtitle": "Sign in to manage your futsal activity.",
  "auth.identifier": "Phone or username",
  "auth.password": "Password",
  "auth.login": "Sign in",
  "auth.noAccount": "Don't have an account?",
  "auth.createAccount": "Create account",
  "auth.registerTitle": "Create your LeagueKick account",
  "auth.registerSubtitle": "Choose a player or venue-owner account. A venue and Premium trial are configured later.",
  "auth.displayName": "Full name",
  "auth.phone": "Phone number",
  "auth.phoneHint": "Example: 0791234567 or +93791234567",
  "auth.usernameOptional": "Username (optional)",
  "auth.accountType": "Account type",
  "auth.player": "Player",
  "auth.venueOwner": "Venue owner",
  "auth.passwordHint": "At least 10 characters",
  "auth.register": "Create account",
  "auth.haveAccount": "Already have an account?",
  "auth.invalidCredentials": "The phone/username or password is incorrect.",
  "auth.duplicateIdentity": "That phone number or username is already in use.",
  "auth.genericError": "We couldn't complete that request. Please try again.",
  "home.title": "Home",
  "home.greeting": "Hello, {name}",
  "home.foundationTitle": "Your LeagueKick account is ready",
  "home.foundationBody": "Language, secure session, role, and connectivity foundations are active.",
  "home.accountRole": "Account role",
  "home.connection": "Connection",
  "home.language": "Language",
  "home.nextTitle": "Next product milestone",
  "home.nextBody": "Venue discovery, live availability, and player booking are the next product milestone.",
  "settings.title": "Settings",
  "settings.language": "Language",
  "settings.account": "Account",
  "settings.security": "Security",
  "settings.sessionProtected": "Your refresh session is stored securely on this device.",
  "validation.required": "This field is required.",
  "validation.password": "Use at least 10 characters.",
  "validation.phone": "Enter a valid Afghanistan phone number.",
  "validation.displayName": "Enter at least 2 characters.",
  "owner.networkError": "Cannot reach the server. Check your connection and try again.",
  "owner.loadError": "We couldn't load your venue setup.",
  "owner.dashboardTitle": "Venue dashboard",
  "owner.dashboardSubtitle": "Manage venue setup, trial status, and your next operating steps.",
  "owner.setupRequiredTitle": "Set up your venue",
  "owner.setupRequiredBody": "Add your venue details, playing area, hours, session duration, and price before starting Premium.",
  "owner.startSetup": "Start venue setup",
  "owner.setupStatus": "Setup",
  "owner.complete": "Complete",
  "owner.incomplete": "Incomplete",
  "owner.subscriptionStatus": "Subscription",
  "owner.subscription.NOT_STARTED": "Trial not started",
  "owner.subscription.TRIAL": "Premium trial",
  "owner.subscription.ACTIVE": "Active",
  "owner.subscription.EXPIRED": "Expired",
  "owner.subscription.CANCELLED": "Cancelled",
  "owner.trialRemaining": "Trial remaining",
  "owner.trialEnds": "Trial ends",
  "owner.reviewSetup": "Review setup and start trial",
  "owner.manageSetup": "View venue setup",
  "owner.trialExpiredTitle": "Premium trial expired",
  "owner.trialExpiredBody": "Your venue data is safe. Subscription reactivation will restore Premium management when billing is enabled.",
  "owner.onboardingTitle": "Set up your venue",
  "owner.stepOf": "Step {current} of {total}",
  "owner.stepAccountTitle": "Owner account",
  "owner.stepAccountBody": "Your venue will be attached to this owner account. One owner account can manage only one venue.",
  "owner.stepIdentityTitle": "Venue identity and contact",
  "owner.venueName": "Venue name",
  "owner.publicPhone": "Public phone",
  "owner.whatsappPhone": "WhatsApp phone (optional)",
  "owner.stepLocationTitle": "Location and address",
  "owner.province": "Province",
  "owner.city": "City",
  "owner.address": "Address",
  "owner.mapPinLater": "A clear address is required now. Map coordinates are optional and can be added later.",
  "owner.stepAreaTitle": "Playing area",
  "owner.stepAreaBody": "Create the first bookable playing area. Additional areas can be added in venue settings later.",
  "owner.areaName": "Playing area name",
  "owner.stepHoursTitle": "Opening hours",
  "owner.stepHoursBody": "Set whether each day is open or closed and define the operating hours.",
  "owner.day.0": "Sunday",
  "owner.day.1": "Monday",
  "owner.day.2": "Tuesday",
  "owner.day.3": "Wednesday",
  "owner.day.4": "Thursday",
  "owner.day.5": "Friday",
  "owner.day.6": "Saturday",
  "owner.closed": "Closed",
  "owner.open": "Open",
  "owner.opensAt": "Opens",
  "owner.closesAt": "Closes",
  "owner.stepPricingTitle": "Session and price",
  "owner.durationMinutes": "Session duration (minutes)",
  "owner.basePriceAfn": "Base price (AFN)",
  "owner.stepPreviewTitle": "Preview venue",
  "owner.location": "Location",
  "owner.previewBody": "Saving creates or updates this account's single venue. It does not start the Premium trial.",
  "owner.saveSetup": "Save venue setup",
  "owner.stepTrialTitle": "Start Premium trial",
  "owner.stepTrialBody": "The 72-hour Premium trial starts only when you press Start trial. The server controls the trial clock.",
  "owner.trialDuration": "Trial duration: 72 hours",
  "owner.startTrial": "Start 3-day Premium trial",
  "owner.goDashboard": "Go to dashboard",
  "owner.back": "Back",
  "owner.continue": "Continue",
  "owner.validationIdentity": "Enter a venue name and valid contact phone.",
  "owner.validationLocation": "Enter province, city, and a clear address.",
  "owner.validationArea": "Enter a playing area name.",
  "owner.validationHours": "Every open day needs a valid opening time before its closing time.",
  "owner.validationPricing": "Session duration must be at least 30 minutes and price cannot be negative.",
  "owner.validationPhone": "Enter a valid Afghanistan venue phone number.",
  "owner.saveError": "We couldn't save the venue setup. Check the fields and try again.",
  "owner.trialAlreadyUsed": "This physical venue has already used its Premium trial.",
  "owner.setupIncomplete": "Complete venue setup before starting the trial.",
  "owner.trialError": "We couldn't start the Premium trial. Please try again.",
  "role.PLAYER": "Player",
  "role.TEAM_MANAGER": "Team manager",
  "role.REFEREE": "Referee",
  "role.VENUE_STAFF": "Venue staff",
  "role.COMPETITION_ADMIN": "Competition admin",
  "role.VENUE_OWNER": "Venue owner",
  "role.PLATFORM_ADMIN": "Platform admin"
} as const;

export type TranslationKey = keyof typeof en;

const fa = {
  "common.appName": "لیگ‌کیک",
  "common.loading": "در حال بارگذاری…",
  "common.retry": "دوباره تلاش کنید",
  "common.save": "ذخیره",
  "common.signOut": "خروج",
  "common.online": "آنلاین",
  "network.offlineTitle": "به اینترنت وصل نیستید",
  "network.offlineBody": "اطلاعات فعلی شما باقی می‌ماند. کارهایی که به سرور نیاز دارند پس از وصل‌شدن دوباره ادامه می‌یابند.",
  "network.backOnline": "دوباره آنلاین شدید",
  "auth.welcomeBack": "خوش آمدید",
  "auth.loginSubtitle": "برای مدیریت فعالیت فوتسال خود وارد شوید.",
  "auth.identifier": "شماره تلفن یا نام کاربری",
  "auth.password": "رمز عبور",
  "auth.login": "ورود",
  "auth.noAccount": "حساب ندارید؟",
  "auth.createAccount": "ایجاد حساب",
  "auth.registerTitle": "حساب لیگ‌کیک خود را بسازید",
  "auth.registerSubtitle": "حساب بازیکن یا مالک سالن را انتخاب کنید. سالن و دوره آزمایشی پریمیوم بعداً تنظیم می‌شود.",
  "auth.displayName": "نام کامل",
  "auth.phone": "شماره تلفن",
  "auth.phoneHint": "نمونه: 0791234567 یا +93791234567",
  "auth.usernameOptional": "نام کاربری (اختیاری)",
  "auth.accountType": "نوع حساب",
  "auth.player": "بازیکن",
  "auth.venueOwner": "مالک سالن",
  "auth.passwordHint": "حداقل ۱۰ نویسه",
  "auth.register": "ایجاد حساب",
  "auth.haveAccount": "از قبل حساب دارید؟",
  "auth.invalidCredentials": "شماره/نام کاربری یا رمز عبور نادرست است.",
  "auth.duplicateIdentity": "این شماره تلفن یا نام کاربری قبلاً استفاده شده است.",
  "auth.genericError": "درخواست تکمیل نشد. لطفاً دوباره تلاش کنید.",
  "home.title": "خانه",
  "home.greeting": "سلام، {name}",
  "home.foundationTitle": "حساب لیگ‌کیک شما آماده است",
  "home.foundationBody": "زبان، نشست امن، نقش کاربری و وضعیت اتصال فعال است.",
  "home.accountRole": "نقش حساب",
  "home.connection": "اتصال",
  "home.language": "زبان",
  "home.nextTitle": "مرحله بعدی محصول",
  "home.nextBody": "کشف سالن، ظرفیت زنده و رزرو بازیکن مرحله بعدی محصول است.",
  "settings.title": "تنظیمات",
  "settings.language": "زبان",
  "settings.account": "حساب",
  "settings.security": "امنیت",
  "settings.sessionProtected": "نشست تازه‌سازی شما به‌صورت امن در این دستگاه نگهداری می‌شود.",
  "validation.required": "این بخش الزامی است.",
  "validation.password": "حداقل ۱۰ نویسه استفاده کنید.",
  "validation.phone": "یک شماره معتبر افغانستان وارد کنید.",
  "validation.displayName": "حداقل ۲ نویسه وارد کنید.",
  "owner.networkError": "ارتباط با سرور برقرار نشد. اتصال اینترنت را بررسی کرده و دوباره تلاش کنید.",
  "owner.loadError": "تنظیمات سالن شما بارگذاری نشد.",
  "owner.dashboardTitle": "داشبورد سالن",
  "owner.dashboardSubtitle": "تنظیم سالن، وضعیت دوره آزمایشی و مراحل بعدی مدیریت را ببینید.",
  "owner.setupRequiredTitle": "سالن خود را تنظیم کنید",
  "owner.setupRequiredBody": "پیش از شروع پریمیوم، مشخصات سالن، زمین بازی، ساعات کاری، مدت جلسه و قیمت را وارد کنید.",
  "owner.startSetup": "شروع تنظیم سالن",
  "owner.setupStatus": "وضعیت تنظیم",
  "owner.complete": "کامل",
  "owner.incomplete": "ناقص",
  "owner.subscriptionStatus": "اشتراک",
  "owner.subscription.NOT_STARTED": "دوره آزمایشی شروع نشده",
  "owner.subscription.TRIAL": "دوره آزمایشی پریمیوم",
  "owner.subscription.ACTIVE": "فعال",
  "owner.subscription.EXPIRED": "منقضی",
  "owner.subscription.CANCELLED": "لغوشده",
  "owner.trialRemaining": "زمان باقی‌مانده آزمایش",
  "owner.trialEnds": "پایان دوره آزمایشی",
  "owner.reviewSetup": "بررسی تنظیمات و شروع آزمایش",
  "owner.manageSetup": "مشاهده تنظیمات سالن",
  "owner.trialExpiredTitle": "دوره آزمایشی پریمیوم پایان یافته است",
  "owner.trialExpiredBody": "اطلاعات سالن شما محفوظ است. پس از فعال‌شدن پرداخت، تمدید اشتراک امکانات پریمیوم را دوباره فعال می‌کند.",
  "owner.onboardingTitle": "تنظیم سالن شما",
  "owner.stepOf": "مرحله {current} از {total}",
  "owner.stepAccountTitle": "حساب مالک",
  "owner.stepAccountBody": "این سالن به همین حساب مالک وصل می‌شود. هر حساب مالک فقط می‌تواند یک سالن را مدیریت کند.",
  "owner.stepIdentityTitle": "هویت و تماس سالن",
  "owner.venueName": "نام سالن",
  "owner.publicPhone": "شماره تماس عمومی",
  "owner.whatsappPhone": "شماره واتساپ (اختیاری)",
  "owner.stepLocationTitle": "موقعیت و آدرس",
  "owner.province": "ولایت",
  "owner.city": "شهر",
  "owner.address": "آدرس",
  "owner.mapPinLater": "فعلاً آدرس واضح الزامی است. مختصات نقشه اختیاری است و بعداً قابل افزودن خواهد بود.",
  "owner.stepAreaTitle": "زمین بازی",
  "owner.stepAreaBody": "اولین زمین قابل رزرو را ایجاد کنید. زمین‌های بیشتر بعداً در تنظیمات سالن اضافه می‌شوند.",
  "owner.areaName": "نام زمین بازی",
  "owner.stepHoursTitle": "ساعات کاری",
  "owner.stepHoursBody": "برای هر روز باز یا بسته بودن و ساعات فعالیت را مشخص کنید.",
  "owner.day.0": "یکشنبه",
  "owner.day.1": "دوشنبه",
  "owner.day.2": "سه‌شنبه",
  "owner.day.3": "چهارشنبه",
  "owner.day.4": "پنجشنبه",
  "owner.day.5": "جمعه",
  "owner.day.6": "شنبه",
  "owner.closed": "بسته",
  "owner.open": "باز",
  "owner.opensAt": "بازشدن",
  "owner.closesAt": "بسته‌شدن",
  "owner.stepPricingTitle": "جلسه و قیمت",
  "owner.durationMinutes": "مدت جلسه (دقیقه)",
  "owner.basePriceAfn": "قیمت پایه (افغانی)",
  "owner.stepPreviewTitle": "پیش‌نمایش سالن",
  "owner.location": "موقعیت",
  "owner.previewBody": "ذخیره، تنها سالن این حساب را ایجاد یا به‌روزرسانی می‌کند و دوره آزمایشی را شروع نمی‌کند.",
  "owner.saveSetup": "ذخیره تنظیمات سالن",
  "owner.stepTrialTitle": "شروع دوره آزمایشی پریمیوم",
  "owner.stepTrialBody": "دوره ۷۲ ساعته پریمیوم فقط با زدن دکمه شروع آغاز می‌شود. زمان آزمایش توسط سرور کنترل می‌شود.",
  "owner.trialDuration": "مدت دوره آزمایشی: ۷۲ ساعت",
  "owner.startTrial": "شروع دوره آزمایشی ۳ روزه",
  "owner.goDashboard": "رفتن به داشبورد",
  "owner.back": "برگشت",
  "owner.continue": "ادامه",
  "owner.validationIdentity": "نام سالن و شماره تماس معتبر را وارد کنید.",
  "owner.validationLocation": "ولایت، شهر و آدرس واضح را وارد کنید.",
  "owner.validationArea": "نام زمین بازی را وارد کنید.",
  "owner.validationHours": "هر روز باز باید زمان بازشدن معتبر و پیش از زمان بسته‌شدن داشته باشد.",
  "owner.validationPricing": "مدت جلسه باید حداقل ۳۰ دقیقه باشد و قیمت نمی‌تواند منفی باشد.",
  "owner.validationPhone": "شماره معتبر افغانستان برای سالن وارد کنید.",
  "owner.saveError": "تنظیمات سالن ذخیره نشد. فیلدها را بررسی کرده و دوباره تلاش کنید.",
  "owner.trialAlreadyUsed": "این سالن فیزیکی قبلاً از دوره آزمایشی پریمیوم استفاده کرده است.",
  "owner.setupIncomplete": "پیش از شروع دوره آزمایشی، تنظیم سالن را کامل کنید.",
  "owner.trialError": "دوره آزمایشی پریمیوم شروع نشد. دوباره تلاش کنید.",
  "role.PLAYER": "بازیکن",
  "role.TEAM_MANAGER": "مدیر تیم",
  "role.REFEREE": "داور",
  "role.VENUE_STAFF": "کارمند سالن",
  "role.COMPETITION_ADMIN": "مدیر رقابت",
  "role.VENUE_OWNER": "مالک سالن",
  "role.PLATFORM_ADMIN": "مدیر پلتفرم"
} satisfies Record<TranslationKey, string>;

const ps = {
  "common.appName": "لیګ‌کېک",
  "common.loading": "در حال بارولو…",
  "common.retry": "بیا هڅه وکړئ",
  "common.save": "خوندي کول",
  "common.signOut": "وتل",
  "common.online": "آنلاین",
  "network.offlineTitle": "تاسو انټرنېټ سره نه یاست نښتي",
  "network.offlineBody": "ستاسو اوسني معلومات پاتې کېږي. هغه کارونه چې سرور ته اړتیا لري د بیا نښلېدو وروسته دوام کوي.",
  "network.backOnline": "بیا آنلاین شوئ",
  "auth.welcomeBack": "ښه راغلاست",
  "auth.loginSubtitle": "د خپل فوتسال فعالیت د مدیریت لپاره ننوځئ.",
  "auth.identifier": "د تلیفون شمېره یا کارن‌نوم",
  "auth.password": "پټنوم",
  "auth.login": "ننوتل",
  "auth.noAccount": "حساب نه لرئ؟",
  "auth.createAccount": "حساب جوړول",
  "auth.registerTitle": "خپل لیګ‌کېک حساب جوړ کړئ",
  "auth.registerSubtitle": "د لوبغاړي یا د میدان د مالک حساب وټاکئ. میدان او Premium آزمایښتي موده وروسته تنظیمېږي.",
  "auth.displayName": "بشپړ نوم",
  "auth.phone": "د تلیفون شمېره",
  "auth.phoneHint": "بېلګه: 0791234567 یا +93791234567",
  "auth.usernameOptional": "کارن‌نوم (اختیاري)",
  "auth.accountType": "د حساب ډول",
  "auth.player": "لوبغاړی",
  "auth.venueOwner": "د میدان مالک",
  "auth.passwordHint": "لږ تر لږه ۱۰ توري",
  "auth.register": "حساب جوړول",
  "auth.haveAccount": "له مخکې حساب لرئ؟",
  "auth.invalidCredentials": "د تلیفون/کارن‌نوم یا پټنوم ناسم دی.",
  "auth.duplicateIdentity": "دا د تلیفون شمېره یا کارن‌نوم له مخکې کارول شوی.",
  "auth.genericError": "غوښتنه بشپړه نه شوه. بیا هڅه وکړئ.",
  "home.title": "کور",
  "home.greeting": "سلام، {name}",
  "home.foundationTitle": "ستاسو لیګ‌کېک حساب چمتو دی",
  "home.foundationBody": "ژبه، خوندي ناسته، رول او د اتصال بنسټ فعال دی.",
  "home.accountRole": "د حساب رول",
  "home.connection": "اتصال",
  "home.language": "ژبه",
  "home.nextTitle": "بل محصول پړاو",
  "home.nextBody": "د میدان موندل، ژوندی موجودیت او د لوبغاړي بک کول د محصول بل پړاو دی.",
  "settings.title": "تنظیمات",
  "settings.language": "ژبه",
  "settings.account": "حساب",
  "settings.security": "امنیت",
  "settings.sessionProtected": "ستاسو د ناستې د نوي کولو معلومات په دې وسیله کې خوندي ساتل کېږي.",
  "validation.required": "دا برخه اړینه ده.",
  "validation.password": "لږ تر لږه ۱۰ توري وکاروئ.",
  "validation.phone": "د افغانستان معتبره شمېره ولیکئ.",
  "validation.displayName": "لږ تر لږه ۲ توري ولیکئ.",
  "owner.networkError": "له سرور سره اړیکه نه نیول کېږي. خپل انټرنېټ وګورئ او بیا هڅه وکړئ.",
  "owner.loadError": "ستاسو د میدان تنظیمات پورته نه شول.",
  "owner.dashboardTitle": "د میدان ډشبورډ",
  "owner.dashboardSubtitle": "د میدان تنظیم، آزمایښتي حالت او د مدیریت راتلونکي ګامونه وګورئ.",
  "owner.setupRequiredTitle": "خپل میدان تنظیم کړئ",
  "owner.setupRequiredBody": "د Premium له پیل مخکې د میدان معلومات، د لوبې ساحه، کاري ساعتونه، د ناستې موده او بیه ولیکئ.",
  "owner.startSetup": "د میدان تنظیم پیل کړئ",
  "owner.setupStatus": "د تنظیم حالت",
  "owner.complete": "بشپړ",
  "owner.incomplete": "نابشپړ",
  "owner.subscriptionStatus": "ګډون",
  "owner.subscription.NOT_STARTED": "آزمایښتي موده نه ده پیل شوې",
  "owner.subscription.TRIAL": "Premium آزمایښتي موده",
  "owner.subscription.ACTIVE": "فعال",
  "owner.subscription.EXPIRED": "پای ته رسېدلی",
  "owner.subscription.CANCELLED": "لغوه شوی",
  "owner.trialRemaining": "پاتې آزمایښتي وخت",
  "owner.trialEnds": "د آزمایښت پای",
  "owner.reviewSetup": "تنظیم وګورئ او آزمایښت پیل کړئ",
  "owner.manageSetup": "د میدان تنظیم وګورئ",
  "owner.trialExpiredTitle": "د Premium آزمایښتي موده پای ته رسېدلې",
  "owner.trialExpiredBody": "ستاسو د میدان معلومات خوندي دي. کله چې تادیات فعال شي، د ګډون بیا فعالول Premium مدیریت بېرته فعالوي.",
  "owner.onboardingTitle": "خپل میدان تنظیم کړئ",
  "owner.stepOf": "ګام {current} له {total}",
  "owner.stepAccountTitle": "د مالک حساب",
  "owner.stepAccountBody": "دا میدان له همدې مالک حساب سره تړل کېږي. هر مالک حساب یوازې یو میدان اداره کولی شي.",
  "owner.stepIdentityTitle": "د میدان پېژندنه او اړیکه",
  "owner.venueName": "د میدان نوم",
  "owner.publicPhone": "عامه تلیفون",
  "owner.whatsappPhone": "د WhatsApp شمېره (اختیاري)",
  "owner.stepLocationTitle": "ځای او پته",
  "owner.province": "ولایت",
  "owner.city": "ښار",
  "owner.address": "پته",
  "owner.mapPinLater": "اوس روښانه پته اړینه ده. د نقشې مختصات اختیاري دي او وروسته ورزیاتېدای شي.",
  "owner.stepAreaTitle": "د لوبې ساحه",
  "owner.stepAreaBody": "لومړنۍ د بک کېدو وړ ساحه جوړه کړئ. نورې ساحې وروسته د میدان په تنظیماتو کې زیاتېدای شي.",
  "owner.areaName": "د لوبې ساحې نوم",
  "owner.stepHoursTitle": "کاري ساعتونه",
  "owner.stepHoursBody": "د هرې ورځې د پرانیستي یا تړلي حالت او کاري ساعتونه وټاکئ.",
  "owner.day.0": "یکشنبه",
  "owner.day.1": "دوشنبه",
  "owner.day.2": "سه‌شنبه",
  "owner.day.3": "چهارشنبه",
  "owner.day.4": "پنجشنبه",
  "owner.day.5": "جمعه",
  "owner.day.6": "شنبه",
  "owner.closed": "تړلی",
  "owner.open": "پرانیستی",
  "owner.opensAt": "پرانیستل",
  "owner.closesAt": "تړل",
  "owner.stepPricingTitle": "ناسته او بیه",
  "owner.durationMinutes": "د ناستې موده (دقیقې)",
  "owner.basePriceAfn": "بنسټیزه بیه (افغانۍ)",
  "owner.stepPreviewTitle": "د میدان مخکتنه",
  "owner.location": "ځای",
  "owner.previewBody": "خوندي کول د دې حساب یوازینی میدان جوړوي یا تازه کوي؛ آزمایښتي موده نه پیلوي.",
  "owner.saveSetup": "د میدان تنظیم خوندي کړئ",
  "owner.stepTrialTitle": "د Premium آزمایښت پیل کړئ",
  "owner.stepTrialBody": "د Premium ۷۲ ساعته آزمایښتي موده یوازې د پیل تڼۍ په وهلو سره پیلېږي. وخت سرور کنټرولوي.",
  "owner.trialDuration": "د آزمایښت موده: ۷۲ ساعته",
  "owner.startTrial": "۳ ورځنی Premium آزمایښت پیل کړئ",
  "owner.goDashboard": "ډشبورډ ته لاړ شئ",
  "owner.back": "شاته",
  "owner.continue": "دوام",
  "owner.validationIdentity": "د میدان نوم او معتبره اړیکه ولیکئ.",
  "owner.validationLocation": "ولایت، ښار او روښانه پته ولیکئ.",
  "owner.validationArea": "د لوبې ساحې نوم ولیکئ.",
  "owner.validationHours": "هره پرانیستې ورځ باید معتبر د پرانیستلو وخت ولري چې د تړلو وخت څخه مخکې وي.",
  "owner.validationPricing": "د ناستې موده باید لږ تر لږه ۳۰ دقیقې وي او بیه منفي کېدای نه شي.",
  "owner.validationPhone": "د افغانستان معتبره د میدان شمېره ولیکئ.",
  "owner.saveError": "د میدان تنظیم خوندي نه شو. معلومات وګورئ او بیا هڅه وکړئ.",
  "owner.trialAlreadyUsed": "دې فزیکي میدان مخکې د Premium آزمایښتي موده کارولې ده.",
  "owner.setupIncomplete": "د آزمایښت له پیل مخکې د میدان تنظیم بشپړ کړئ.",
  "owner.trialError": "د Premium آزمایښتي موده پیل نه شوه. بیا هڅه وکړئ.",
  "role.PLAYER": "لوبغاړی",
  "role.TEAM_MANAGER": "د ټیم مدیر",
  "role.REFEREE": "ریفري",
  "role.VENUE_STAFF": "د میدان کارکوونکی",
  "role.COMPETITION_ADMIN": "د سیالۍ مدیر",
  "role.VENUE_OWNER": "د میدان مالک",
  "role.PLATFORM_ADMIN": "د پلاتفورم مدیر"
} satisfies Record<TranslationKey, string>;

const resources: Record<LanguageCode, Record<TranslationKey, string>> = { "fa-AF": fa, "ps-AF": ps, en };

export function isRtlLanguage(language: LanguageCode): boolean {
  return language === "fa-AF" || language === "ps-AF";
}

export function translate(language: LanguageCode, key: TranslationKey, params?: Record<string, string | number>): string {
  let value: string = resources[language][key] ?? en[key];
  if (!params) return value;
  for (const [name, replacement] of Object.entries(params)) {
    value = value.replaceAll(`{${name}}`, String(replacement));
  }
  return value;
}

export function getLanguage(language: LanguageCode) {
  return languages.find((item) => item.code === language) ?? languages[0];
}
