export type LanguageCode = "fa-AF" | "ps-AF" | "en";

export const languages = [
  { code: "fa-AF", nativeName: "دری", rtl: true },
  { code: "ps-AF", nativeName: "پښتو", rtl: true },
  { code: "en", nativeName: "English", rtl: false },
] as const satisfies ReadonlyArray<{ code: LanguageCode; nativeName: string; rtl: boolean }>;

export const defaultLanguage: LanguageCode = "fa-AF";

const en = {
  "common.appName": "Futsal",
  "common.loading": "Loading…",
  "common.retry": "Try again",
  "common.save": "Save",
  "common.signOut": "Sign out",
  "common.online": "Online",
  "common.showPassword": "Show password",
  "common.hidePassword": "Hide password",
  "network.offlineTitle": "You are offline",
  "network.offlineBody": "Your current information stays visible. Actions that need the server will resume when you reconnect.",
  "network.backOnline": "Back online",
  "auth.welcomeBack": "Welcome back",
  "auth.loginSubtitle": "Sign in to manage your futsal activity.",
  "auth.identifier": "Phone or username",
  "auth.password": "Password",
  "auth.login": "Sign in",
  "auth.noAccount": "Don't have an account?",
  "auth.createAccount": "Create account",
  "auth.registerTitle": "Create your Futsal account",
  "auth.registerSubtitle": "Choose a player or venue-owner account. A venue and Premium trial are configured later.",
  "auth.displayName": "Full name",
  "auth.phone": "Phone number",
  "auth.phoneHint": "Example: 0791234567 or +93791234567",
  "auth.usernameOptional": "Username (optional)",
  "auth.accountType": "Account type",
  "auth.player": "Player",
  "auth.venueOwner": "Venue owner",
  "auth.passwordHint": "Use at least 8 characters and one special character.",
  "auth.placeholderIdentifier": "Enter phone number or username",
  "auth.placeholderPassword": "Enter your password",
  "auth.placeholderDisplayName": "Example: Ahmad Rahimi",
  "auth.placeholderPhone": "Example: 0791234567",
  "auth.placeholderUsername": "Example: ahmad123",
  "auth.placeholderNewPassword": "Create a secure password",
  "auth.passwordGuideTitle": "Password requirements",
  "auth.passwordRuleLength": "At least 8 characters",
  "auth.passwordRuleSpecial": "At least one special character, for example ! @ # $",
  "auth.passwordRuleLettersNumbers": "Letters and numbers are allowed.",
  "auth.register": "Create account",
  "auth.haveAccount": "Already have an account?",
  "auth.invalidCredentials": "The phone/username or password is incorrect.",
  "auth.duplicateIdentity": "That phone number or username is already in use.",
  "auth.genericError": "We couldn't complete that request. Please try again.",
  "home.title": "Home",
  "home.greeting": "Hello, {name}",
  "home.foundationTitle": "Your Futsal account is ready",
  "home.foundationBody": "Language, secure session, role, and connectivity foundations are active.",
  "home.accountRole": "Account role",
  "home.connection": "Connection",
  "home.language": "Language",
  "home.nextTitle": "Next product milestone",
  "home.nextBody": "Venue discovery, live availability, and player booking are the next product milestone.",
  "profile.title": "Profile",
  "profile.subtitle": "Manage your personal details, language, security, and shortcuts.",
  "profile.headerSubtitle": "Futsal booking & community",
  "profile.openProfile": "Open profile",
  "settings.title": "Settings",
  "settings.language": "Language",
  "settings.account": "Account",
  "settings.security": "Security",
  "settings.sessionProtected": "Your refresh session is stored securely on this device.",
  "settings.subtitle": "Manage your account, preferences, security, and shortcuts in one place.",
  "settings.accountSubtitle": "Your Futsal identity and access details.",
  "settings.username": "Username",
  "settings.preferences": "Preferences",
  "settings.preferencesSubtitle": "Personalize how Futsal works for you.",
  "settings.languageBody": "Choose the language used across the app.",
  "settings.notifications": "Notifications",
  "settings.notificationsBody": "Control booking, promotion, post, and push alerts.",
  "settings.securitySubtitle": "Keep your account session current and protected.",
  "settings.sessionProtectedTitle": "Secure session",
  "settings.secureSession": "Protected",
  "settings.refreshSession": "Refresh secure session",
  "settings.connectionChecking": "Checking connection",
  "settings.connectionOnline": "Online",
  "settings.connectionOffline": "Offline",
  "settings.quickAccess": "Quick access",
  "settings.quickAccessSubtitle": "Jump directly to the tools you use most.",
  "settings.ownerScheduleBody": "Review bookings, manual reservations, and blocked time.",
  "settings.ownerPromotionsBody": "Manage discounted empty-slot offers.",
  "settings.ownerPostsBody": "Publish and manage venue updates.",
  "settings.playerVenuesBody": "Discover futsal venues and live availability.",
  "settings.playerBookingsBody": "Review upcoming and previous bookings.",
  "settings.playerFeedBody": "See promotions and updates from futsal venues.",
  "settings.app": "App information",
  "settings.appSubtitle": "Product and connection details.",
  "settings.product": "Product",
  "settings.region": "Launch region",
  "settings.regionValue": "Afghanistan",
  "settings.signOutTitle": "Sign out of this device",
  "settings.signOutBody": "Your local session will be cleared securely.",
  "validation.required": "This field is required.",
  "validation.password": "Use at least 8 characters and include at least one special character.",
  "validation.phone": "Enter a valid Afghanistan phone number.",
  "validation.displayName": "Enter at least 2 characters.",
  "owner.networkError": "Cannot reach the server. Check your connection and try again.",
  "owner.loadError": "We couldn't load your venue setup.",
  "owner.dashboardTitle": "Venue dashboard",
  "owner.dashboardSubtitle": "Manage venue setup, trial status, and your next operating steps.",
  "owner.setupRequiredTitle": "Set up your venue",
  "owner.setupRequiredBody": "Add your venue details, playing area, hours, session duration, and price before starting Premium.",
  "owner.startSetup": "Start venue setup",
  "owner.setupStatus": "Setup",
  "owner.complete": "Complete",
  "owner.incomplete": "Incomplete",
  "owner.subscriptionStatus": "Subscription",
  "owner.subscription.NOT_STARTED": "Trial not started",
  "owner.subscription.TRIAL": "Premium trial",
  "owner.subscription.ACTIVE": "Active",
  "owner.subscription.EXPIRED": "Expired",
  "owner.subscription.CANCELLED": "Cancelled",
  "owner.trialRemaining": "Trial remaining",
  "owner.trialEnds": "Trial ends",
  "owner.reviewSetup": "Review setup and start trial",
  "owner.manageSetup": "View venue setup",
  "owner.trialExpiredTitle": "Premium trial expired",
  "owner.trialExpiredBody": "Your venue data is safe. Subscription reactivation will restore Premium management when billing is enabled.",
  "owner.onboardingTitle": "Set up your venue",
  "owner.stepOf": "Step {current} of {total}",
  "owner.stepAccountTitle": "Owner account",
  "owner.stepAccountBody": "Your venue will be attached to this owner account. One owner account can manage only one venue.",
  "owner.stepIdentityTitle": "Venue identity and contact",
  "owner.venueName": "Venue name",
  "owner.publicPhone": "Public phone",
  "owner.whatsappPhone": "WhatsApp phone (optional)",
  "owner.stepLocationTitle": "Location and address",
  "owner.province": "Province",
  "owner.city": "City",
  "owner.address": "Address",
  "owner.mapPinLater": "A clear address is required now. Map coordinates are optional and can be added later.",
  "owner.stepAreaTitle": "Playing area",
  "owner.stepAreaBody": "Create the first bookable playing area. Additional areas can be added in venue settings later.",
  "owner.areaName": "Playing area name",
  "owner.stepHoursTitle": "Opening hours",
  "owner.stepHoursBody": "Set whether each day is open or closed and define the operating hours.",
  "owner.day.0": "Sunday",
  "owner.day.1": "Monday",
  "owner.day.2": "Tuesday",
  "owner.day.3": "Wednesday",
  "owner.day.4": "Thursday",
  "owner.day.5": "Friday",
  "owner.day.6": "Saturday",
  "owner.closed": "Closed",
  "owner.open": "Open",
  "owner.opensAt": "Opens",
  "owner.closesAt": "Closes",
  "owner.stepPricingTitle": "Session and price",
  "owner.durationMinutes": "Session duration (minutes)",
  "owner.basePriceAfn": "Base price (AFN)",
  "owner.stepPreviewTitle": "Preview venue",
  "owner.location": "Location",
  "owner.previewBody": "Saving creates or updates this account's single venue. It does not start the Premium trial.",
  "owner.saveSetup": "Save venue setup",
  "owner.stepTrialTitle": "Start Premium trial",
  "owner.stepTrialBody": "The 72-hour Premium trial starts only when you press Start trial. The server controls the trial clock.",
  "owner.trialDuration": "Trial duration: 72 hours",
  "owner.startTrial": "Start 3-day Premium trial",
  "owner.goDashboard": "Go to dashboard",
  "owner.back": "Back",
  "owner.continue": "Continue",
  "owner.validationIdentity": "Enter a venue name and valid contact phone.",
  "owner.validationLocation": "Enter province, city, and a clear address.",
  "owner.validationArea": "Enter a playing area name.",
  "owner.validationHours": "Every open day needs a valid opening time before its closing time.",
  "owner.validationPricing": "Session duration must be at least 30 minutes and price cannot be negative.",
  "owner.validationPhone": "Enter a valid Afghanistan venue phone number.",
  "owner.saveError": "We couldn't save the venue setup. Check the fields and try again.",
  "owner.trialAlreadyUsed": "This physical venue has already used its Premium trial.",
  "owner.identityLocked": "Venue identity is locked after the trial starts. Contact support for a legitimate identity correction.",
  "owner.setupIncomplete": "Complete venue setup before starting the trial.",
  "owner.trialError": "We couldn't start the Premium trial. Please try again.",
  "booking.venuesTitle": "Venues",
  "booking.venuesSubtitle": "Find a venue with live bookable futsal time.",
  "booking.cityFilter": "City (optional)",
  "booking.search": "Search venues",
  "booking.noVenues": "No bookable venues match this search.",
  "booking.loadVenuesError": "We couldn't load venues.",
  "booking.viewAvailability": "View live availability",
  "booking.date": "Date",
  "booking.offlineNoCache": "You're offline and no cached availability is saved for this date.",
  "booking.loadAvailabilityError": "We couldn't load live availability.",
  "booking.cachedAvailability": "Cached availability",
  "booking.cachedAvailabilityBody": "These times may be outdated. Reconnect for live availability before booking.",
  "booking.noSlots": "No available slots for this date.",
  "booking.bookNow": "Book this slot",
  "booking.liveRequired": "Live connection required",
  "booking.confirmTitle": "Confirm booking",
  "booking.slotTaken": "Another player booked this slot. Return to availability for updated times.",
  "booking.confirmNeedsInternet": "A live internet connection is required to confirm a booking.",
  "booking.confirmError": "We couldn't confirm the booking. Please try again.",
  "booking.serverRecheck": "Futsal will recheck availability and price on the server before confirmation.",
  "booking.noteOptional": "Note (optional)",
  "booking.confirmButton": "Confirm booking",
  "booking.backToVenue": "Back to availability",
  "booking.myBookings": "My bookings",
  "booking.loadBookingsError": "We couldn't load your bookings.",
  "booking.cancelError": "We couldn't cancel that booking.",
  "booking.noBookings": "You don't have any bookings yet.",
  "booking.status.PENDING": "Pending",
  "booking.status.CONFIRMED": "Confirmed",
  "booking.status.CANCELLED": "Cancelled",
  "booking.cancel": "Cancel booking",
  "booking.quickStart": "Book futsal time",
  "booking.quickStartBody": "Browse live venue availability and reserve a suitable time.",
  "booking.findVenue": "Find a venue",
  "schedule.title": "Schedule",
  "schedule.subtitle": "One calendar for online bookings, phone/walk-in bookings, and blocked time.",
  "schedule.refresh": "Refresh schedule",
  "schedule.addManual": "Add manual booking",
  "schedule.blockTime": "Block time",
  "schedule.loadError": "We couldn't load the venue schedule.",
  "schedule.empty": "No bookings or blocks for this date.",
  "schedule.onlinePlayer": "Online player",
  "schedule.source.ONLINE": "Online",
  "schedule.source.MANUAL": "Manual",
  "schedule.cancelBooking": "Cancel booking",
  "schedule.blocked": "Blocked",
  "schedule.unblock": "Unblock time",
  "schedule.cancelError": "We couldn't cancel the booking.",
  "schedule.unblockError": "We couldn't remove the block.",
  "schedule.manualTitle": "Manual booking",
  "schedule.area": "Playing area",
  "schedule.startTime": "Start time",
  "schedule.endTime": "End time",
  "schedule.customerName": "Customer name",
  "schedule.customerPhone": "Customer phone (optional)",
  "schedule.price": "Price AFN (optional)",
  "schedule.createManual": "Create manual booking",
  "schedule.conflict": "That time overlaps an existing booking or block.",
  "schedule.subscriptionRequired": "An active Premium trial or subscription is required for new schedule changes.",
  "schedule.manualError": "We couldn't create the manual booking.",
  "schedule.blockTitle": "Block venue time",
  "schedule.reasonOptional": "Reason (optional)",
  "schedule.createBlock": "Block this time",
  "schedule.blockError": "We couldn't block that time.",
  "feed.title": "Feed",
  "feed.subtitle": "Venue updates and real discounted futsal slots.",
  "feed.all": "All",
  "feed.following": "Following",
  "feed.loadError": "We couldn't load the feed.",
  "feed.followingEmpty": "Follow venues to see their updates here.",
  "feed.empty": "There are no public venue updates yet.",
  "feed.bookPromotion": "View discounted slot",
  "feed.openPost": "Open update",
  "feed.postLoadError": "This venue update could not be loaded.",
  "feed.promotionUnavailable": "This promotion is no longer available.",
  "feed.postTitle": "Venue update",
  "feed.openCta": "Open",
  "feed.followError": "We couldn't update your follow setting.",
  "feed.follow": "Follow venue",
  "feed.unfollow": "Unfollow venue",
  "feed.followers": "{count} followers",
  "feed.promotedSlot": "Discounted slot",
  "notifications.title": "Notifications",
  "notifications.subtitle": "Booking activity and updates from venues you follow.",
  "notifications.loadError": "We couldn't load your notifications.",
  "notifications.preferenceError": "We couldn't save that notification preference.",
  "notifications.preferences": "Notification preferences",
  "notifications.inApp": "In-app notifications",
  "notifications.push": "Push notifications",
  "notifications.promotions": "Discounted-slot alerts",
  "notifications.venuePosts": "Venue-post alerts",
  "notifications.empty": "You don't have any notifications yet.",
  "notifications.unread": "Unread",
  "notifications.type.BOOKING_CONFIRMED": "Booking confirmed",
  "notifications.type.BOOKING_CANCELLED": "Booking cancelled",
  "notifications.type.SLOT_PROMOTION": "Discounted slot",
  "notifications.type.VENUE_POST": "Venue update",
  "notifications.body.BOOKING_CONFIRMED": "Your futsal booking is confirmed. Tap to view your bookings.",
  "notifications.body.BOOKING_CANCELLED": "A booking was cancelled. Tap to view your bookings.",
  "notifications.body.SLOT_PROMOTION": "A venue you follow published a discounted slot.",
  "notifications.body.VENUE_POST": "A venue you follow published a new update.",
  "ownerMarketing.marketingTitle": "Marketing",
  "ownerMarketing.marketingBody": "Promote empty capacity and publish venue updates to followers.",
  "ownerMarketing.promotionsTitle": "Promotions",
  "ownerMarketing.promotionsSubtitle": "Discount real future slots without creating separate inventory.",
  "ownerMarketing.createPromotion": "Create promotion",
  "ownerMarketing.loadPromotionsError": "We couldn't load your promotions.",
  "ownerMarketing.closePromotionError": "We couldn't close that promotion.",
  "ownerMarketing.noPromotions": "You haven't created any promotions yet.",
  "ownerMarketing.promotionStatus.ACTIVE": "Active",
  "ownerMarketing.promotionStatus.CLOSED": "Closed",
  "ownerMarketing.promotionStatus.EXPIRED": "Expired",
  "ownerMarketing.closePromotion": "Close promotion",
  "ownerMarketing.createPromotionBody": "Choose a currently available slot and set a lower temporary price.",
  "ownerMarketing.refreshSlots": "Refresh available slots",
  "ownerMarketing.entitlementRequired": "An active Premium trial or subscription is required for marketing actions.",
  "ownerMarketing.loadSlotsError": "We couldn't load promotable slots.",
  "ownerMarketing.noPromotableSlots": "No unpromoted live slots are available for this date.",
  "ownerMarketing.defaultPromotionTitle": "Limited futsal discount",
  "ownerMarketing.selectedSlot": "Selected slot",
  "ownerMarketing.promotionTitle": "Promotion title",
  "ownerMarketing.discountedPrice": "Discounted price (AFN)",
  "ownerMarketing.discountValidation": "Enter a price lower than the current slot price.",
  "ownerMarketing.notifyFollowers": "Notify venue followers",
  "ownerMarketing.publishPromotion": "Publish promotion",
  "ownerMarketing.slotNoLongerAvailable": "That slot is no longer available. Refresh the list.",
  "ownerMarketing.promotionExists": "This slot already has an active promotion.",
  "ownerMarketing.createPromotionError": "We couldn't publish the promotion.",
  "ownerMarketing.postsTitle": "Venue posts",
  "ownerMarketing.postsSubtitle": "Publish immediate venue updates with useful booking CTAs.",
  "ownerMarketing.createPost": "Create post",
  "ownerMarketing.loadPostsError": "We couldn't load your venue posts.",
  "ownerMarketing.postStatusError": "We couldn't change the post status.",
  "ownerMarketing.noPosts": "You haven't published any venue posts yet.",
  "ownerMarketing.postStatus.PUBLISHED": "Published",
  "ownerMarketing.postStatus.UNPUBLISHED": "Unpublished",
  "ownerMarketing.unpublish": "Unpublish",
  "ownerMarketing.publish": "Publish",
  "ownerMarketing.createPostBody": "Write a short venue update and optionally link it to your venue or an active promotion.",
  "ownerMarketing.postBody": "Post text",
  "ownerMarketing.imageUrl": "Image URL (optional)",
  "ownerMarketing.cta": "Call to action",
  "ownerMarketing.cta.NONE": "No CTA",
  "ownerMarketing.cta.VENUE": "Open venue",
  "ownerMarketing.cta.PROMOTION": "Open promotion",
  "ownerMarketing.choosePromotion": "Choose active promotion",
  "ownerMarketing.noActivePromotions": "There are no active promotions to link.",
  "ownerMarketing.notifyFollowersPost": "Notify followers about this post",
  "ownerMarketing.publishPost": "Publish post",
  "ownerMarketing.invalidPostCta": "Choose a valid active promotion for this CTA.",
  "ownerMarketing.createPostError": "We couldn't publish the venue post.",
  "role.PLAYER": "Player",
  "role.TEAM_MANAGER": "Team manager",
  "role.REFEREE": "Referee",
  "role.VENUE_STAFF": "Venue staff",
  "role.COMPETITION_ADMIN": "Competition admin",
  "role.VENUE_OWNER": "Venue owner",
  "role.PLATFORM_ADMIN": "Platform admin"
} as const;

export type TranslationKey = keyof typeof en;

const fa = {
  "common.appName": "فوتسال",
  "common.loading": "در حال بارگذاری…",
  "common.retry": "دوباره تلاش کنید",
  "common.save": "ذخیره",
  "common.signOut": "خروج",
  "common.online": "آنلاین",
  "common.showPassword": "نمایش رمز عبور",
  "common.hidePassword": "پنهان‌کردن رمز عبور",
  "network.offlineTitle": "به اینترنت وصل نیستید",
  "network.offlineBody": "اطلاعات فعلی شما باقی می‌ماند. کارهایی که به سرور نیاز دارند پس از وصل‌شدن دوباره ادامه می‌یابند.",
  "network.backOnline": "دوباره آنلاین شدید",
  "auth.welcomeBack": "خوش آمدید",
  "auth.loginSubtitle": "برای مدیریت فعالیت فوتسال خود وارد شوید.",
  "auth.identifier": "شماره تلفن یا نام کاربری",
  "auth.password": "رمز عبور",
  "auth.login": "ورود",
  "auth.noAccount": "حساب ندارید؟",
  "auth.createAccount": "ایجاد حساب",
  "auth.registerTitle": "حساب فوتسال خود را بسازید",
  "auth.registerSubtitle": "حساب بازیکن یا مالک سالن را انتخاب کنید. سالن و دوره آزمایشی پریمیوم بعداً تنظیم می‌شود.",
  "auth.displayName": "نام کامل",
  "auth.phone": "شماره تلفن",
  "auth.phoneHint": "نمونه: 0791234567 یا +93791234567",
  "auth.usernameOptional": "نام کاربری (اختیاری)",
  "auth.accountType": "نوع حساب",
  "auth.player": "بازیکن",
  "auth.venueOwner": "مالک سالن",
  "auth.passwordHint": "حداقل ۸ نویسه و یک نویسهٔ ویژه استفاده کنید.",
  "auth.placeholderIdentifier": "شماره تلفن یا نام کاربری را وارد کنید",
  "auth.placeholderPassword": "رمز عبور خود را وارد کنید",
  "auth.placeholderDisplayName": "نمونه: احمد رحیمی",
  "auth.placeholderPhone": "نمونه: 0791234567",
  "auth.placeholderUsername": "نمونه: ahmad123",
  "auth.placeholderNewPassword": "یک رمز عبور امن بسازید",
  "auth.passwordGuideTitle": "شرایط رمز عبور",
  "auth.passwordRuleLength": "حداقل ۸ نویسه",
  "auth.passwordRuleSpecial": "حداقل یک نویسهٔ ویژه، مانند ! @ # $",
  "auth.passwordRuleLettersNumbers": "استفاده از حروف و اعداد مجاز است.",
  "auth.register": "ایجاد حساب",
  "auth.haveAccount": "از قبل حساب دارید؟",
  "auth.invalidCredentials": "شماره/نام کاربری یا رمز عبور نادرست است.",
  "auth.duplicateIdentity": "این شماره تلفن یا نام کاربری قبلاً استفاده شده است.",
  "auth.genericError": "درخواست تکمیل نشد. لطفاً دوباره تلاش کنید.",
  "home.title": "خانه",
  "home.greeting": "سلام، {name}",
  "home.foundationTitle": "حساب فوتسال شما آماده است",
  "home.foundationBody": "زبان، نشست امن، نقش کاربری و وضعیت اتصال فعال است.",
  "home.accountRole": "نقش حساب",
  "home.connection": "اتصال",
  "home.language": "زبان",
  "home.nextTitle": "مرحله بعدی محصول",
  "home.nextBody": "کشف سالن، ظرفیت زنده و رزرو بازیکن مرحله بعدی محصول است.",
  "profile.title": "پروفایل",
  "profile.subtitle": "اطلاعات شخصی، زبان، امنیت و دسترسی‌های سریع خود را مدیریت کنید.",
  "profile.headerSubtitle": "رزرو و جامعه فوتسال",
  "profile.openProfile": "بازکردن پروفایل",
  "settings.title": "تنظیمات",
  "settings.language": "زبان",
  "settings.account": "حساب",
  "settings.security": "امنیت",
  "settings.sessionProtected": "نشست تازه‌سازی شما به‌صورت امن در این دستگاه نگهداری می‌شود.",
  "settings.subtitle": "حساب، ترجیحات، امنیت و دسترسی‌های سریع خود را در یک جا مدیریت کنید.",
  "settings.accountSubtitle": "هویت و جزئیات دسترسی حساب فوتسال شما.",
  "settings.username": "نام کاربری",
  "settings.preferences": "ترجیحات",
  "settings.preferencesSubtitle": "نحوه کار فوتسال را برای خود شخصی‌سازی کنید.",
  "settings.languageBody": "زبان مورد استفاده در سراسر برنامه را انتخاب کنید.",
  "settings.notifications": "اعلان‌ها",
  "settings.notificationsBody": "اعلان‌های رزرو، تخفیف، پست و پوش را مدیریت کنید.",
  "settings.securitySubtitle": "نشست حساب خود را تازه و محافظت‌شده نگه دارید.",
  "settings.sessionProtectedTitle": "نشست امن",
  "settings.secureSession": "محافظت‌شده",
  "settings.refreshSession": "تازه‌سازی نشست امن",
  "settings.connectionChecking": "در حال بررسی اتصال",
  "settings.connectionOnline": "آنلاین",
  "settings.connectionOffline": "آفلاین",
  "settings.quickAccess": "دسترسی سریع",
  "settings.quickAccessSubtitle": "مستقیماً به ابزارهایی بروید که بیشتر استفاده می‌کنید.",
  "settings.ownerScheduleBody": "رزروها، رزروهای دستی و زمان‌های مسدود را بررسی کنید.",
  "settings.ownerPromotionsBody": "تخفیف‌های وقت‌های خالی را مدیریت کنید.",
  "settings.ownerPostsBody": "خبرهای سالن را منتشر و مدیریت کنید.",
  "settings.playerVenuesBody": "سالن‌های فوتسال و ظرفیت زنده را پیدا کنید.",
  "settings.playerBookingsBody": "رزروهای آینده و گذشته خود را ببینید.",
  "settings.playerFeedBody": "تخفیف‌ها و خبرهای سالن‌های فوتسال را ببینید.",
  "settings.app": "اطلاعات برنامه",
  "settings.appSubtitle": "جزئیات محصول و اتصال.",
  "settings.product": "محصول",
  "settings.region": "منطقه آغاز",
  "settings.regionValue": "افغانستان",
  "settings.signOutTitle": "خروج از این دستگاه",
  "settings.signOutBody": "نشست محلی شما به‌صورت امن پاک می‌شود.",
  "validation.required": "این بخش الزامی است.",
  "validation.password": "حداقل ۸ نویسه و دست‌کم یک نویسهٔ ویژه استفاده کنید.",
  "validation.phone": "یک شماره معتبر افغانستان وارد کنید.",
  "validation.displayName": "حداقل ۲ نویسه وارد کنید.",
  "owner.networkError": "ارتباط با سرور برقرار نشد. اتصال اینترنت را بررسی کرده و دوباره تلاش کنید.",
  "owner.loadError": "تنظیمات سالن شما بارگذاری نشد.",
  "owner.dashboardTitle": "داشبورد سالن",
  "owner.dashboardSubtitle": "تنظیم سالن، وضعیت دوره آزمایشی و مراحل بعدی مدیریت را ببینید.",
  "owner.setupRequiredTitle": "سالن خود را تنظیم کنید",
  "owner.setupRequiredBody": "پیش از شروع پریمیوم، مشخصات سالن، زمین بازی، ساعات کاری، مدت جلسه و قیمت را وارد کنید.",
  "owner.startSetup": "شروع تنظیم سالن",
  "owner.setupStatus": "وضعیت تنظیم",
  "owner.complete": "کامل",
  "owner.incomplete": "ناقص",
  "owner.subscriptionStatus": "اشتراک",
  "owner.subscription.NOT_STARTED": "دوره آزمایشی شروع نشده",
  "owner.subscription.TRIAL": "دوره آزمایشی پریمیوم",
  "owner.subscription.ACTIVE": "فعال",
  "owner.subscription.EXPIRED": "منقضی",
  "owner.subscription.CANCELLED": "لغوشده",
  "owner.trialRemaining": "زمان باقی‌مانده آزمایش",
  "owner.trialEnds": "پایان دوره آزمایشی",
  "owner.reviewSetup": "بررسی تنظیمات و شروع آزمایش",
  "owner.manageSetup": "مشاهده تنظیمات سالن",
  "owner.trialExpiredTitle": "دوره آزمایشی پریمیوم پایان یافته است",
  "owner.trialExpiredBody": "اطلاعات سالن شما محفوظ است. پس از فعال‌شدن پرداخت، تمدید اشتراک امکانات پریمیوم را دوباره فعال می‌کند.",
  "owner.onboardingTitle": "تنظیم سالن شما",
  "owner.stepOf": "مرحله {current} از {total}",
  "owner.stepAccountTitle": "حساب مالک",
  "owner.stepAccountBody": "این سالن به همین حساب مالک وصل می‌شود. هر حساب مالک فقط می‌تواند یک سالن را مدیریت کند.",
  "owner.stepIdentityTitle": "هویت و تماس سالن",
  "owner.venueName": "نام سالن",
  "owner.publicPhone": "شماره تماس عمومی",
  "owner.whatsappPhone": "شماره واتساپ (اختیاری)",
  "owner.stepLocationTitle": "موقعیت و آدرس",
  "owner.province": "ولایت",
  "owner.city": "شهر",
  "owner.address": "آدرس",
  "owner.mapPinLater": "فعلاً آدرس واضح الزامی است. مختصات نقشه اختیاری است و بعداً قابل افزودن خواهد بود.",
  "owner.stepAreaTitle": "زمین بازی",
  "owner.stepAreaBody": "اولین زمین قابل رزرو را ایجاد کنید. زمین‌های بیشتر بعداً در تنظیمات سالن اضافه می‌شوند.",
  "owner.areaName": "نام زمین بازی",
  "owner.stepHoursTitle": "ساعات کاری",
  "owner.stepHoursBody": "برای هر روز باز یا بسته بودن و ساعات فعالیت را مشخص کنید.",
  "owner.day.0": "یکشنبه",
  "owner.day.1": "دوشنبه",
  "owner.day.2": "سه‌شنبه",
  "owner.day.3": "چهارشنبه",
  "owner.day.4": "پنجشنبه",
  "owner.day.5": "جمعه",
  "owner.day.6": "شنبه",
  "owner.closed": "بسته",
  "owner.open": "باز",
  "owner.opensAt": "بازشدن",
  "owner.closesAt": "بسته‌شدن",
  "owner.stepPricingTitle": "جلسه و قیمت",
  "owner.durationMinutes": "مدت جلسه (دقیقه)",
  "owner.basePriceAfn": "قیمت پایه (افغانی)",
  "owner.stepPreviewTitle": "پیش‌نمایش سالن",
  "owner.location": "موقعیت",
  "owner.previewBody": "ذخیره، تنها سالن این حساب را ایجاد یا به‌روزرسانی می‌کند و دوره آزمایشی را شروع نمی‌کند.",
  "owner.saveSetup": "ذخیره تنظیمات سالن",
  "owner.stepTrialTitle": "شروع دوره آزمایشی پریمیوم",
  "owner.stepTrialBody": "دوره ۷۲ ساعته پریمیوم فقط با زدن دکمه شروع آغاز می‌شود. زمان آزمایش توسط سرور کنترل می‌شود.",
  "owner.trialDuration": "مدت دوره آزمایشی: ۷۲ ساعت",
  "owner.startTrial": "شروع دوره آزمایشی ۳ روزه",
  "owner.goDashboard": "رفتن به داشبورد",
  "owner.back": "برگشت",
  "owner.continue": "ادامه",
  "owner.validationIdentity": "نام سالن و شماره تماس معتبر را وارد کنید.",
  "owner.validationLocation": "ولایت، شهر و آدرس واضح را وارد کنید.",
  "owner.validationArea": "نام زمین بازی را وارد کنید.",
  "owner.validationHours": "هر روز باز باید زمان بازشدن معتبر و پیش از زمان بسته‌شدن داشته باشد.",
  "owner.validationPricing": "مدت جلسه باید حداقل ۳۰ دقیقه باشد و قیمت نمی‌تواند منفی باشد.",
  "owner.validationPhone": "شماره معتبر افغانستان برای سالن وارد کنید.",
  "owner.saveError": "تنظیمات سالن ذخیره نشد. فیلدها را بررسی کرده و دوباره تلاش کنید.",
  "owner.trialAlreadyUsed": "این سالن فیزیکی قبلاً از دوره آزمایشی پریمیوم استفاده کرده است.",
  "owner.identityLocked": "هویت سالن پس از شروع دوره آزمایشی قفل می‌شود. برای اصلاح واقعی هویت با پشتیبانی تماس بگیرید.",
  "owner.setupIncomplete": "پیش از شروع دوره آزمایشی، تنظیم سالن را کامل کنید.",
  "owner.trialError": "دوره آزمایشی پریمیوم شروع نشد. دوباره تلاش کنید.",
  "booking.venuesTitle": "سالن‌ها",
  "booking.venuesSubtitle": "سالنی را با وقت زنده و قابل رزرو فوتسال پیدا کنید.",
  "booking.cityFilter": "شهر (اختیاری)",
  "booking.search": "جستجوی سالن‌ها",
  "booking.noVenues": "هیچ سالن قابل رزروی با این جستجو پیدا نشد.",
  "booking.loadVenuesError": "سالن‌ها بارگذاری نشدند.",
  "booking.viewAvailability": "مشاهده وقت‌های زنده",
  "booking.date": "تاریخ",
  "booking.offlineNoCache": "آفلاین هستید و برای این تاریخ اطلاعات ذخیره‌شده‌ای وجود ندارد.",
  "booking.loadAvailabilityError": "وقت‌های زنده بارگذاری نشد.",
  "booking.cachedAvailability": "وقت‌های ذخیره‌شده",
  "booking.cachedAvailabilityBody": "این زمان‌ها ممکن است قدیمی باشند. پیش از رزرو برای اطلاعات زنده دوباره وصل شوید.",
  "booking.noSlots": "برای این تاریخ وقت خالی وجود ندارد.",
  "booking.bookNow": "رزرو این وقت",
  "booking.liveRequired": "اتصال زنده لازم است",
  "booking.confirmTitle": "تأیید رزرو",
  "booking.slotTaken": "بازیکن دیگری این وقت را رزرو کرد. برای دیدن زمان‌های تازه به فهرست وقت‌ها برگردید.",
  "booking.confirmNeedsInternet": "برای تأیید رزرو اتصال زنده اینترنت لازم است.",
  "booking.confirmError": "رزرو تأیید نشد. دوباره تلاش کنید.",
  "booking.serverRecheck": "پیش از تأیید، فوتسال موجودیت و قیمت را دوباره در سرور بررسی می‌کند.",
  "booking.noteOptional": "یادداشت (اختیاری)",
  "booking.confirmButton": "تأیید رزرو",
  "booking.backToVenue": "برگشت به وقت‌ها",
  "booking.myBookings": "رزروهای من",
  "booking.loadBookingsError": "رزروهای شما بارگذاری نشد.",
  "booking.cancelError": "لغو رزرو انجام نشد.",
  "booking.noBookings": "هنوز هیچ رزروی ندارید.",
  "booking.status.PENDING": "در انتظار",
  "booking.status.CONFIRMED": "تأییدشده",
  "booking.status.CANCELLED": "لغوشده",
  "booking.cancel": "لغو رزرو",
  "booking.quickStart": "رزرو وقت فوتسال",
  "booking.quickStartBody": "وقت زنده سالن‌ها را ببینید و زمان مناسب را رزرو کنید.",
  "booking.findVenue": "پیداکردن سالن",
  "schedule.title": "برنامه سالن",
  "schedule.subtitle": "یک تقویم برای رزروهای آنلاین، تلفنی/حضوری و زمان‌های مسدود.",
  "schedule.refresh": "تازه‌سازی برنامه",
  "schedule.addManual": "افزودن رزرو دستی",
  "schedule.blockTime": "مسدودکردن زمان",
  "schedule.loadError": "برنامه سالن بارگذاری نشد.",
  "schedule.empty": "برای این تاریخ رزرو یا زمان مسدودی وجود ندارد.",
  "schedule.onlinePlayer": "بازیکن آنلاین",
  "schedule.source.ONLINE": "آنلاین",
  "schedule.source.MANUAL": "دستی",
  "schedule.cancelBooking": "لغو رزرو",
  "schedule.blocked": "مسدود",
  "schedule.unblock": "بازکردن زمان",
  "schedule.cancelError": "رزرو لغو نشد.",
  "schedule.unblockError": "زمان مسدود حذف نشد.",
  "schedule.manualTitle": "رزرو دستی",
  "schedule.area": "زمین بازی",
  "schedule.startTime": "زمان شروع",
  "schedule.endTime": "زمان پایان",
  "schedule.customerName": "نام مشتری",
  "schedule.customerPhone": "شماره مشتری (اختیاری)",
  "schedule.price": "قیمت افغانی (اختیاری)",
  "schedule.createManual": "ایجاد رزرو دستی",
  "schedule.conflict": "این زمان با یک رزرو یا مسدودی موجود تداخل دارد.",
  "schedule.subscriptionRequired": "برای تغییرات جدید برنامه، دوره آزمایشی یا اشتراک پریمیوم فعال لازم است.",
  "schedule.manualError": "رزرو دستی ایجاد نشد.",
  "schedule.blockTitle": "مسدودکردن زمان سالن",
  "schedule.reasonOptional": "دلیل (اختیاری)",
  "schedule.createBlock": "مسدودکردن این زمان",
  "schedule.blockError": "این زمان مسدود نشد.",
  "feed.title": "فید",
  "feed.subtitle": "خبرهای سالن‌ها و وقت‌های واقعی فوتسال با تخفیف.",
  "feed.all": "همه",
  "feed.following": "دنبال‌شده‌ها",
  "feed.loadError": "فید بارگذاری نشد.",
  "feed.followingEmpty": "سالن‌ها را دنبال کنید تا خبرهای‌شان را اینجا ببینید.",
  "feed.empty": "هنوز خبر عمومی از سالن‌ها وجود ندارد.",
  "feed.bookPromotion": "مشاهده وقت تخفیف‌دار",
  "feed.openPost": "بازکردن خبر",
  "feed.postLoadError": "این خبر سالن بارگذاری نشد.",
  "feed.promotionUnavailable": "این تخفیف دیگر فعال نیست.",
  "feed.postTitle": "خبر سالن",
  "feed.openCta": "بازکردن",
  "feed.followError": "تنظیم دنبال‌کردن ذخیره نشد.",
  "feed.follow": "دنبال‌کردن سالن",
  "feed.unfollow": "لغو دنبال‌کردن",
  "feed.followers": "{count} دنبال‌کننده",
  "feed.promotedSlot": "وقت تخفیف‌دار",
  "notifications.title": "اعلان‌ها",
  "notifications.subtitle": "فعالیت رزرو و خبرهای سالن‌هایی که دنبال می‌کنید.",
  "notifications.loadError": "اعلان‌های شما بارگذاری نشد.",
  "notifications.preferenceError": "تنظیم اعلان ذخیره نشد.",
  "notifications.preferences": "تنظیمات اعلان",
  "notifications.inApp": "اعلان داخل برنامه",
  "notifications.push": "اعلان پوش",
  "notifications.promotions": "خبر تخفیف وقت‌ها",
  "notifications.venuePosts": "خبر پست‌های سالن",
  "notifications.empty": "هنوز هیچ اعلانی ندارید.",
  "notifications.unread": "خوانده‌نشده",
  "notifications.type.BOOKING_CONFIRMED": "رزرو تأیید شد",
  "notifications.type.BOOKING_CANCELLED": "رزرو لغو شد",
  "notifications.type.SLOT_PROMOTION": "وقت تخفیف‌دار",
  "notifications.type.VENUE_POST": "خبر سالن",
  "notifications.body.BOOKING_CONFIRMED": "رزرو فوتسال شما تأیید شد. برای دیدن رزروها لمس کنید.",
  "notifications.body.BOOKING_CANCELLED": "یک رزرو لغو شد. برای دیدن رزروها لمس کنید.",
  "notifications.body.SLOT_PROMOTION": "سالنی که دنبال می‌کنید یک وقت تخفیف‌دار منتشر کرد.",
  "notifications.body.VENUE_POST": "سالنی که دنبال می‌کنید خبر تازه‌ای منتشر کرد.",
  "ownerMarketing.marketingTitle": "بازاریابی",
  "ownerMarketing.marketingBody": "وقت‌های خالی را تبلیغ کنید و خبرهای سالن را برای دنبال‌کنندگان منتشر کنید.",
  "ownerMarketing.promotionsTitle": "تخفیف‌ها",
  "ownerMarketing.promotionsSubtitle": "برای وقت‌های واقعی آینده تخفیف بدهید، بدون ایجاد موجودی جداگانه.",
  "ownerMarketing.createPromotion": "ایجاد تخفیف",
  "ownerMarketing.loadPromotionsError": "تخفیف‌های شما بارگذاری نشد.",
  "ownerMarketing.closePromotionError": "این تخفیف بسته نشد.",
  "ownerMarketing.noPromotions": "هنوز هیچ تخفیفی ایجاد نکرده‌اید.",
  "ownerMarketing.promotionStatus.ACTIVE": "فعال",
  "ownerMarketing.promotionStatus.CLOSED": "بسته",
  "ownerMarketing.promotionStatus.EXPIRED": "منقضی",
  "ownerMarketing.closePromotion": "بستن تخفیف",
  "ownerMarketing.createPromotionBody": "یک وقت خالی زنده را انتخاب کرده و قیمت موقت پایین‌تری تعیین کنید.",
  "ownerMarketing.refreshSlots": "تازه‌سازی وقت‌های خالی",
  "ownerMarketing.entitlementRequired": "برای کارهای بازاریابی دوره آزمایشی یا اشتراک پریمیوم فعال لازم است.",
  "ownerMarketing.loadSlotsError": "وقت‌های قابل تخفیف بارگذاری نشد.",
  "ownerMarketing.noPromotableSlots": "برای این تاریخ وقت زنده بدون تخفیف وجود ندارد.",
  "ownerMarketing.defaultPromotionTitle": "تخفیف محدود فوتسال",
  "ownerMarketing.selectedSlot": "وقت انتخاب‌شده",
  "ownerMarketing.promotionTitle": "عنوان تخفیف",
  "ownerMarketing.discountedPrice": "قیمت تخفیف‌دار (افغانی)",
  "ownerMarketing.discountValidation": "قیمتی کمتر از قیمت فعلی وقت وارد کنید.",
  "ownerMarketing.notifyFollowers": "خبرکردن دنبال‌کنندگان سالن",
  "ownerMarketing.publishPromotion": "انتشار تخفیف",
  "ownerMarketing.slotNoLongerAvailable": "این وقت دیگر خالی نیست. فهرست را تازه کنید.",
  "ownerMarketing.promotionExists": "این وقت از قبل یک تخفیف فعال دارد.",
  "ownerMarketing.createPromotionError": "تخفیف منتشر نشد.",
  "ownerMarketing.postsTitle": "پست‌های سالن",
  "ownerMarketing.postsSubtitle": "خبرهای فوری سالن را با لینک‌های مفید رزرو منتشر کنید.",
  "ownerMarketing.createPost": "ایجاد پست",
  "ownerMarketing.loadPostsError": "پست‌های سالن بارگذاری نشد.",
  "ownerMarketing.postStatusError": "وضعیت پست تغییر نکرد.",
  "ownerMarketing.noPosts": "هنوز هیچ پستی منتشر نکرده‌اید.",
  "ownerMarketing.postStatus.PUBLISHED": "منتشرشده",
  "ownerMarketing.postStatus.UNPUBLISHED": "منتشرنشده",
  "ownerMarketing.unpublish": "لغو انتشار",
  "ownerMarketing.publish": "انتشار",
  "ownerMarketing.createPostBody": "یک خبر کوتاه بنویسید و در صورت نیاز آن را به سالن یا تخفیف فعال پیوند دهید.",
  "ownerMarketing.postBody": "متن پست",
  "ownerMarketing.imageUrl": "آدرس تصویر (اختیاری)",
  "ownerMarketing.cta": "دکمه اقدام",
  "ownerMarketing.cta.NONE": "بدون دکمه",
  "ownerMarketing.cta.VENUE": "بازکردن سالن",
  "ownerMarketing.cta.PROMOTION": "بازکردن تخفیف",
  "ownerMarketing.choosePromotion": "انتخاب تخفیف فعال",
  "ownerMarketing.noActivePromotions": "تخفیف فعالی برای پیوند وجود ندارد.",
  "ownerMarketing.notifyFollowersPost": "دنبال‌کنندگان را از این پست خبر کنید",
  "ownerMarketing.publishPost": "انتشار پست",
  "ownerMarketing.invalidPostCta": "برای این دکمه یک تخفیف فعال معتبر انتخاب کنید.",
  "ownerMarketing.createPostError": "پست سالن منتشر نشد.",
  "role.PLAYER": "بازیکن",
  "role.TEAM_MANAGER": "مدیر تیم",
  "role.REFEREE": "داور",
  "role.VENUE_STAFF": "کارمند سالن",
  "role.COMPETITION_ADMIN": "مدیر رقابت",
  "role.VENUE_OWNER": "مالک سالن",
  "role.PLATFORM_ADMIN": "مدیر پلتفرم"
} satisfies Record<TranslationKey, string>;

const ps = {
  "common.appName": "فوتسال",
  "common.loading": "در حال بارولو…",
  "common.retry": "بیا هڅه وکړئ",
  "common.save": "خوندي کول",
  "common.signOut": "وتل",
  "common.online": "آنلاین",
  "common.showPassword": "پټنوم ښکاره کړئ",
  "common.hidePassword": "پټنوم پټ کړئ",
  "network.offlineTitle": "تاسو انټرنېټ سره نه یاست نښتي",
  "network.offlineBody": "ستاسو اوسني معلومات پاتې کېږي. هغه کارونه چې سرور ته اړتیا لري د بیا نښلېدو وروسته دوام کوي.",
  "network.backOnline": "بیا آنلاین شوئ",
  "auth.welcomeBack": "ښه راغلاست",
  "auth.loginSubtitle": "د خپل فوتسال فعالیت د مدیریت لپاره ننوځئ.",
  "auth.identifier": "د تلیفون شمېره یا کارن‌نوم",
  "auth.password": "پټنوم",
  "auth.login": "ننوتل",
  "auth.noAccount": "حساب نه لرئ؟",
  "auth.createAccount": "حساب جوړول",
  "auth.registerTitle": "خپل فوتسال حساب جوړ کړئ",
  "auth.registerSubtitle": "د لوبغاړي یا د میدان د مالک حساب وټاکئ. میدان او Premium آزمایښتي موده وروسته تنظیمېږي.",
  "auth.displayName": "بشپړ نوم",
  "auth.phone": "د تلیفون شمېره",
  "auth.phoneHint": "بېلګه: 0791234567 یا +93791234567",
  "auth.usernameOptional": "کارن‌نوم (اختیاري)",
  "auth.accountType": "د حساب ډول",
  "auth.player": "لوبغاړی",
  "auth.venueOwner": "د میدان مالک",
  "auth.passwordHint": "لږ تر لږه ۸ توري او یو ځانګړی نښه وکاروئ.",
  "auth.placeholderIdentifier": "د تلیفون شمېره یا کارن‌نوم ولیکئ",
  "auth.placeholderPassword": "خپل پټنوم ولیکئ",
  "auth.placeholderDisplayName": "بېلګه: احمد رحیمي",
  "auth.placeholderPhone": "بېلګه: 0791234567",
  "auth.placeholderUsername": "بېلګه: ahmad123",
  "auth.placeholderNewPassword": "خوندي پټنوم جوړ کړئ",
  "auth.passwordGuideTitle": "د پټنوم شرطونه",
  "auth.passwordRuleLength": "لږ تر لږه ۸ توري",
  "auth.passwordRuleSpecial": "لږ تر لږه یوه ځانګړې نښه، لکه ! @ # $",
  "auth.passwordRuleLettersNumbers": "توري او شمېرې کارول کېدای شي.",
  "auth.register": "حساب جوړول",
  "auth.haveAccount": "له مخکې حساب لرئ؟",
  "auth.invalidCredentials": "د تلیفون/کارن‌نوم یا پټنوم ناسم دی.",
  "auth.duplicateIdentity": "دا د تلیفون شمېره یا کارن‌نوم له مخکې کارول شوی.",
  "auth.genericError": "غوښتنه بشپړه نه شوه. بیا هڅه وکړئ.",
  "home.title": "کور",
  "home.greeting": "سلام، {name}",
  "home.foundationTitle": "ستاسو فوتسال حساب چمتو دی",
  "home.foundationBody": "ژبه، خوندي ناسته، رول او د اتصال بنسټ فعال دی.",
  "home.accountRole": "د حساب رول",
  "home.connection": "اتصال",
  "home.language": "ژبه",
  "home.nextTitle": "بل محصول پړاو",
  "home.nextBody": "د میدان موندل، ژوندی موجودیت او د لوبغاړي بک کول د محصول بل پړاو دی.",
  "profile.title": "پروفایل",
  "profile.subtitle": "خپل شخصي معلومات، ژبه، امنیت او چټک لاسرسی اداره کړئ.",
  "profile.headerSubtitle": "د فوتسال بک او ټولنه",
  "profile.openProfile": "پروفایل پرانیزئ",
  "settings.title": "تنظیمات",
  "settings.language": "ژبه",
  "settings.account": "حساب",
  "settings.security": "امنیت",
  "settings.sessionProtected": "ستاسو د ناستې د نوي کولو معلومات په دې وسیله کې خوندي ساتل کېږي.",
  "settings.subtitle": "خپل حساب، غوره توبونه، امنیت او چټک لاسرسی په یوه ځای کې اداره کړئ.",
  "settings.accountSubtitle": "ستاسو د فوتسال هویت او د لاسرسي معلومات.",
  "settings.username": "کارن‌نوم",
  "settings.preferences": "غوره توبونه",
  "settings.preferencesSubtitle": "فوتسال د خپلې اړتیا سره سم تنظیم کړئ.",
  "settings.languageBody": "هغه ژبه وټاکئ چې په ټول اپ کې کارول کېږي.",
  "settings.notifications": "خبرتیاوې",
  "settings.notificationsBody": "د بک، تخفیف، پوسټ او Push خبرتیاوې اداره کړئ.",
  "settings.securitySubtitle": "خپل حساب ناسته تازه او خوندي وساتئ.",
  "settings.sessionProtectedTitle": "خوندي ناسته",
  "settings.secureSession": "خوندي",
  "settings.refreshSession": "خوندي ناسته تازه کړئ",
  "settings.connectionChecking": "اتصال کتل کېږي",
  "settings.connectionOnline": "آنلاین",
  "settings.connectionOffline": "آفلاین",
  "settings.quickAccess": "چټک لاسرسی",
  "settings.quickAccessSubtitle": "مستقیم هغو وسیلو ته لاړ شئ چې ډېر یې کاروئ.",
  "settings.ownerScheduleBody": "بکونه، لاسي بکونه او بند وختونه وګورئ.",
  "settings.ownerPromotionsBody": "د خالي وختونو تخفیفي وړاندیزونه اداره کړئ.",
  "settings.ownerPostsBody": "د میدان خبرونه خپاره او اداره کړئ.",
  "settings.playerVenuesBody": "د فوتسال میدانونه او ژوندی موجودیت پیدا کړئ.",
  "settings.playerBookingsBody": "راتلونکي او پخواني بکونه وګورئ.",
  "settings.playerFeedBody": "د فوتسال میدانونو تخفیفونه او خبرونه وګورئ.",
  "settings.app": "د اپ معلومات",
  "settings.appSubtitle": "د محصول او اتصال معلومات.",
  "settings.product": "محصول",
  "settings.region": "د پیل سیمه",
  "settings.regionValue": "افغانستان",
  "settings.signOutTitle": "له دې وسیلې ووځئ",
  "settings.signOutBody": "ستاسو محلي ناسته به په خوندي ډول پاکه شي.",
  "validation.required": "دا برخه اړینه ده.",
  "validation.password": "لږ تر لږه ۸ توري او یوه ځانګړې نښه وکاروئ.",
  "validation.phone": "د افغانستان معتبره شمېره ولیکئ.",
  "validation.displayName": "لږ تر لږه ۲ توري ولیکئ.",
  "owner.networkError": "له سرور سره اړیکه نه نیول کېږي. خپل انټرنېټ وګورئ او بیا هڅه وکړئ.",
  "owner.loadError": "ستاسو د میدان تنظیمات پورته نه شول.",
  "owner.dashboardTitle": "د میدان ډشبورډ",
  "owner.dashboardSubtitle": "د میدان تنظیم، آزمایښتي حالت او د مدیریت راتلونکي ګامونه وګورئ.",
  "owner.setupRequiredTitle": "خپل میدان تنظیم کړئ",
  "owner.setupRequiredBody": "د Premium له پیل مخکې د میدان معلومات، د لوبې ساحه، کاري ساعتونه، د ناستې موده او بیه ولیکئ.",
  "owner.startSetup": "د میدان تنظیم پیل کړئ",
  "owner.setupStatus": "د تنظیم حالت",
  "owner.complete": "بشپړ",
  "owner.incomplete": "نابشپړ",
  "owner.subscriptionStatus": "ګډون",
  "owner.subscription.NOT_STARTED": "آزمایښتي موده نه ده پیل شوې",
  "owner.subscription.TRIAL": "Premium آزمایښتي موده",
  "owner.subscription.ACTIVE": "فعال",
  "owner.subscription.EXPIRED": "پای ته رسېدلی",
  "owner.subscription.CANCELLED": "لغوه شوی",
  "owner.trialRemaining": "پاتې آزمایښتي وخت",
  "owner.trialEnds": "د آزمایښت پای",
  "owner.reviewSetup": "تنظیم وګورئ او آزمایښت پیل کړئ",
  "owner.manageSetup": "د میدان تنظیم وګورئ",
  "owner.trialExpiredTitle": "د Premium آزمایښتي موده پای ته رسېدلې",
  "owner.trialExpiredBody": "ستاسو د میدان معلومات خوندي دي. کله چې تادیات فعال شي، د ګډون بیا فعالول Premium مدیریت بېرته فعالوي.",
  "owner.onboardingTitle": "خپل میدان تنظیم کړئ",
  "owner.stepOf": "ګام {current} له {total}",
  "owner.stepAccountTitle": "د مالک حساب",
  "owner.stepAccountBody": "دا میدان له همدې مالک حساب سره تړل کېږي. هر مالک حساب یوازې یو میدان اداره کولی شي.",
  "owner.stepIdentityTitle": "د میدان پېژندنه او اړیکه",
  "owner.venueName": "د میدان نوم",
  "owner.publicPhone": "عامه تلیفون",
  "owner.whatsappPhone": "د WhatsApp شمېره (اختیاري)",
  "owner.stepLocationTitle": "ځای او پته",
  "owner.province": "ولایت",
  "owner.city": "ښار",
  "owner.address": "پته",
  "owner.mapPinLater": "اوس روښانه پته اړینه ده. د نقشې مختصات اختیاري دي او وروسته ورزیاتېدای شي.",
  "owner.stepAreaTitle": "د لوبې ساحه",
  "owner.stepAreaBody": "لومړنۍ د بک کېدو وړ ساحه جوړه کړئ. نورې ساحې وروسته د میدان په تنظیماتو کې زیاتېدای شي.",
  "owner.areaName": "د لوبې ساحې نوم",
  "owner.stepHoursTitle": "کاري ساعتونه",
  "owner.stepHoursBody": "د هرې ورځې د پرانیستي یا تړلي حالت او کاري ساعتونه وټاکئ.",
  "owner.day.0": "یکشنبه",
  "owner.day.1": "دوشنبه",
  "owner.day.2": "سه‌شنبه",
  "owner.day.3": "چهارشنبه",
  "owner.day.4": "پنجشنبه",
  "owner.day.5": "جمعه",
  "owner.day.6": "شنبه",
  "owner.closed": "تړلی",
  "owner.open": "پرانیستی",
  "owner.opensAt": "پرانیستل",
  "owner.closesAt": "تړل",
  "owner.stepPricingTitle": "ناسته او بیه",
  "owner.durationMinutes": "د ناستې موده (دقیقې)",
  "owner.basePriceAfn": "بنسټیزه بیه (افغانۍ)",
  "owner.stepPreviewTitle": "د میدان مخکتنه",
  "owner.location": "ځای",
  "owner.previewBody": "خوندي کول د دې حساب یوازینی میدان جوړوي یا تازه کوي؛ آزمایښتي موده نه پیلوي.",
  "owner.saveSetup": "د میدان تنظیم خوندي کړئ",
  "owner.stepTrialTitle": "د Premium آزمایښت پیل کړئ",
  "owner.stepTrialBody": "د Premium ۷۲ ساعته آزمایښتي موده یوازې د پیل تڼۍ په وهلو سره پیلېږي. وخت سرور کنټرولوي.",
  "owner.trialDuration": "د آزمایښت موده: ۷۲ ساعته",
  "owner.startTrial": "۳ ورځنی Premium آزمایښت پیل کړئ",
  "owner.goDashboard": "ډشبورډ ته لاړ شئ",
  "owner.back": "شاته",
  "owner.continue": "دوام",
  "owner.validationIdentity": "د میدان نوم او معتبره اړیکه ولیکئ.",
  "owner.validationLocation": "ولایت، ښار او روښانه پته ولیکئ.",
  "owner.validationArea": "د لوبې ساحې نوم ولیکئ.",
  "owner.validationHours": "هره پرانیستې ورځ باید معتبر د پرانیستلو وخت ولري چې د تړلو وخت څخه مخکې وي.",
  "owner.validationPricing": "د ناستې موده باید لږ تر لږه ۳۰ دقیقې وي او بیه منفي کېدای نه شي.",
  "owner.validationPhone": "د افغانستان معتبره د میدان شمېره ولیکئ.",
  "owner.saveError": "د میدان تنظیم خوندي نه شو. معلومات وګورئ او بیا هڅه وکړئ.",
  "owner.trialAlreadyUsed": "دې فزیکي میدان مخکې د Premium آزمایښتي موده کارولې ده.",
  "owner.identityLocked": "د آزمایښت له پیل وروسته د میدان هویت قفل کېږي. د رښتینې سمونې لپاره له ملاتړ سره اړیکه ونیسئ.",
  "owner.setupIncomplete": "د آزمایښت له پیل مخکې د میدان تنظیم بشپړ کړئ.",
  "owner.trialError": "د Premium آزمایښتي موده پیل نه شوه. بیا هڅه وکړئ.",
  "booking.venuesTitle": "میدانونه",
  "booking.venuesSubtitle": "د ژوندیو او د بک کېدو وړ وختونو سره د فوتسال میدان پیدا کړئ.",
  "booking.cityFilter": "ښار (اختیاري)",
  "booking.search": "میدانونه ولټوئ",
  "booking.noVenues": "د دې لټون لپاره د بک کېدو وړ میدان ونه موندل شو.",
  "booking.loadVenuesError": "میدانونه پورته نه شول.",
  "booking.viewAvailability": "ژوندی موجودیت وګورئ",
  "booking.date": "نېټه",
  "booking.offlineNoCache": "تاسو آفلاین یاست او د دې نېټې لپاره ساتل شوی موجودیت نشته.",
  "booking.loadAvailabilityError": "ژوندی موجودیت پورته نه شو.",
  "booking.cachedAvailability": "ساتل شوی موجودیت",
  "booking.cachedAvailabilityBody": "دا وختونه ښايي زاړه وي. د بک کولو مخکې د ژوندیو معلوماتو لپاره بیا وصل شئ.",
  "booking.noSlots": "د دې نېټې لپاره خالي وخت نشته.",
  "booking.bookNow": "دا وخت بک کړئ",
  "booking.liveRequired": "ژوندۍ اړیکه اړینه ده",
  "booking.confirmTitle": "بک کول تایید کړئ",
  "booking.slotTaken": "بل لوبغاړي دا وخت بک کړ. د نوو وختونو لپاره موجودیت ته بېرته لاړ شئ.",
  "booking.confirmNeedsInternet": "د بک تایید لپاره ژوندۍ انټرنېټ اړیکه اړینه ده.",
  "booking.confirmError": "بک تایید نه شو. بیا هڅه وکړئ.",
  "booking.serverRecheck": "فوتسال به د تایید مخکې موجودیت او بیه په سرور کې بیا وګوري.",
  "booking.noteOptional": "یادښت (اختیاري)",
  "booking.confirmButton": "بک تایید کړئ",
  "booking.backToVenue": "موجودیت ته بېرته",
  "booking.myBookings": "زما بکونه",
  "booking.loadBookingsError": "ستاسو بکونه پورته نه شول.",
  "booking.cancelError": "بک لغوه نه شو.",
  "booking.noBookings": "تر اوسه مو هېڅ بک نشته.",
  "booking.status.PENDING": "په تمه",
  "booking.status.CONFIRMED": "تایید شوی",
  "booking.status.CANCELLED": "لغوه شوی",
  "booking.cancel": "بک لغوه کړئ",
  "booking.quickStart": "د فوتسال وخت بک کړئ",
  "booking.quickStartBody": "د میدانونو ژوندی موجودیت وګورئ او مناسب وخت بک کړئ.",
  "booking.findVenue": "میدان پیدا کړئ",
  "schedule.title": "مهالویش",
  "schedule.subtitle": "د آنلاین، تلیفوني/حضوري بکونو او بند وخت لپاره یو ګډ تقویم.",
  "schedule.refresh": "مهالویش تازه کړئ",
  "schedule.addManual": "لاسي بک زیات کړئ",
  "schedule.blockTime": "وخت بند کړئ",
  "schedule.loadError": "د میدان مهالویش پورته نه شو.",
  "schedule.empty": "د دې نېټې لپاره بک یا بند وخت نشته.",
  "schedule.onlinePlayer": "آنلاین لوبغاړی",
  "schedule.source.ONLINE": "آنلاین",
  "schedule.source.MANUAL": "لاسي",
  "schedule.cancelBooking": "بک لغوه کړئ",
  "schedule.blocked": "بند",
  "schedule.unblock": "وخت خلاص کړئ",
  "schedule.cancelError": "بک لغوه نه شو.",
  "schedule.unblockError": "بند وخت لرې نه شو.",
  "schedule.manualTitle": "لاسي بک",
  "schedule.area": "د لوبې ساحه",
  "schedule.startTime": "د پیل وخت",
  "schedule.endTime": "د پای وخت",
  "schedule.customerName": "د پیرودونکي نوم",
  "schedule.customerPhone": "د پیرودونکي شمېره (اختیاري)",
  "schedule.price": "بیه افغانۍ (اختیاري)",
  "schedule.createManual": "لاسي بک جوړ کړئ",
  "schedule.conflict": "دا وخت له موجود بک یا بند وخت سره ټکر لري.",
  "schedule.subscriptionRequired": "د نوو مهالویش بدلونونو لپاره فعال Premium آزمایښت یا ګډون اړین دی.",
  "schedule.manualError": "لاسي بک جوړ نه شو.",
  "schedule.blockTitle": "د میدان وخت بند کړئ",
  "schedule.reasonOptional": "دلیل (اختیاري)",
  "schedule.createBlock": "دا وخت بند کړئ",
  "schedule.blockError": "دا وخت بند نه شو.",
  "feed.title": "فید",
  "feed.subtitle": "د میدانونو خبرونه او رښتیني تخفیفي فوتسال وختونه.",
  "feed.all": "ټول",
  "feed.following": "تعقیب شوي",
  "feed.loadError": "فید پورته نه شو.",
  "feed.followingEmpty": "میدانونه تعقیب کړئ تر څو خبرونه یې دلته ووینئ.",
  "feed.empty": "تر اوسه د میدانونو عام خبرونه نشته.",
  "feed.bookPromotion": "تخفیفي وخت وګورئ",
  "feed.openPost": "خبر پرانیزئ",
  "feed.postLoadError": "د میدان دا خبر پورته نه شو.",
  "feed.promotionUnavailable": "دا تخفیف نور فعال نه دی.",
  "feed.postTitle": "د میدان خبر",
  "feed.openCta": "پرانیزئ",
  "feed.followError": "د تعقیب تنظیم خوندي نه شو.",
  "feed.follow": "میدان تعقیب کړئ",
  "feed.unfollow": "تعقیب بند کړئ",
  "feed.followers": "{count} تعقیبوونکي",
  "feed.promotedSlot": "تخفیفي وخت",
  "notifications.title": "خبرتیاوې",
  "notifications.subtitle": "د بک فعالیت او د تعقیب شوو میدانونو خبرونه.",
  "notifications.loadError": "ستاسو خبرتیاوې پورته نه شوې.",
  "notifications.preferenceError": "د خبرتیا تنظیم خوندي نه شو.",
  "notifications.preferences": "د خبرتیا تنظیمات",
  "notifications.inApp": "د اپ دننه خبرتیاوې",
  "notifications.push": "Push خبرتیاوې",
  "notifications.promotions": "د تخفیفي وخت خبرتیاوې",
  "notifications.venuePosts": "د میدان د پوسټ خبرتیاوې",
  "notifications.empty": "تر اوسه هېڅ خبرتیا نه لرئ.",
  "notifications.unread": "نه لوستل شوې",
  "notifications.type.BOOKING_CONFIRMED": "بک تایید شو",
  "notifications.type.BOOKING_CANCELLED": "بک لغوه شو",
  "notifications.type.SLOT_PROMOTION": "تخفیفي وخت",
  "notifications.type.VENUE_POST": "د میدان خبر",
  "notifications.body.BOOKING_CONFIRMED": "ستاسو د فوتسال بک تایید شو. د بکونو د لیدلو لپاره یې پرانیزئ.",
  "notifications.body.BOOKING_CANCELLED": "یو بک لغوه شو. د بکونو د لیدلو لپاره یې پرانیزئ.",
  "notifications.body.SLOT_PROMOTION": "هغه میدان چې تعقیبوئ یو تخفیفي وخت خپور کړ.",
  "notifications.body.VENUE_POST": "هغه میدان چې تعقیبوئ نوی خبر خپور کړ.",
  "ownerMarketing.marketingTitle": "بازارموندنه",
  "ownerMarketing.marketingBody": "خالي وختونه تبلیغ کړئ او د میدان خبرونه تعقیبوونکو ته خپاره کړئ.",
  "ownerMarketing.promotionsTitle": "تخفیفونه",
  "ownerMarketing.promotionsSubtitle": "د راتلونکو رښتینو وختونو بیه راکمه کړئ، بې له جلا موجودۍ جوړولو.",
  "ownerMarketing.createPromotion": "تخفیف جوړ کړئ",
  "ownerMarketing.loadPromotionsError": "ستاسو تخفیفونه پورته نه شول.",
  "ownerMarketing.closePromotionError": "دا تخفیف بند نه شو.",
  "ownerMarketing.noPromotions": "تر اوسه مو هېڅ تخفیف نه دی جوړ کړی.",
  "ownerMarketing.promotionStatus.ACTIVE": "فعال",
  "ownerMarketing.promotionStatus.CLOSED": "بند",
  "ownerMarketing.promotionStatus.EXPIRED": "پای ته رسېدلی",
  "ownerMarketing.closePromotion": "تخفیف بند کړئ",
  "ownerMarketing.createPromotionBody": "یو اوسنی خالي وخت وټاکئ او لنډمهاله ټیټه بیه ورته وټاکئ.",
  "ownerMarketing.refreshSlots": "خالي وختونه تازه کړئ",
  "ownerMarketing.entitlementRequired": "د بازارموندنې لپاره فعال Premium آزمایښت یا ګډون اړین دی.",
  "ownerMarketing.loadSlotsError": "د تخفیف وړ وختونه پورته نه شول.",
  "ownerMarketing.noPromotableSlots": "د دې نېټې لپاره بې‌تخفیفه ژوندی خالي وخت نشته.",
  "ownerMarketing.defaultPromotionTitle": "محدود فوتسال تخفیف",
  "ownerMarketing.selectedSlot": "ټاکل شوی وخت",
  "ownerMarketing.promotionTitle": "د تخفیف سرلیک",
  "ownerMarketing.discountedPrice": "تخفیفي بیه (افغانۍ)",
  "ownerMarketing.discountValidation": "له اوسني قیمت څخه ټیټه بیه ولیکئ.",
  "ownerMarketing.notifyFollowers": "د میدان تعقیبوونکي خبر کړئ",
  "ownerMarketing.publishPromotion": "تخفیف خپور کړئ",
  "ownerMarketing.slotNoLongerAvailable": "دا وخت نور خالي نه دی. لست تازه کړئ.",
  "ownerMarketing.promotionExists": "دا وخت له مخکې فعال تخفیف لري.",
  "ownerMarketing.createPromotionError": "تخفیف خپور نه شو.",
  "ownerMarketing.postsTitle": "د میدان پوسټونه",
  "ownerMarketing.postsSubtitle": "د میدان سمدستي خبرونه د ګټورو بک لینکونو سره خپاره کړئ.",
  "ownerMarketing.createPost": "پوسټ جوړ کړئ",
  "ownerMarketing.loadPostsError": "د میدان پوسټونه پورته نه شول.",
  "ownerMarketing.postStatusError": "د پوسټ حالت بدل نه شو.",
  "ownerMarketing.noPosts": "تر اوسه مو هېڅ پوسټ نه دی خپور کړی.",
  "ownerMarketing.postStatus.PUBLISHED": "خپور شوی",
  "ownerMarketing.postStatus.UNPUBLISHED": "نه دی خپور",
  "ownerMarketing.unpublish": "خپرول بند کړئ",
  "ownerMarketing.publish": "خپور کړئ",
  "ownerMarketing.createPostBody": "لنډ خبر ولیکئ او که اړتیا وي له میدان یا فعال تخفیف سره یې ونښلوئ.",
  "ownerMarketing.postBody": "د پوسټ متن",
  "ownerMarketing.imageUrl": "د انځور URL (اختیاري)",
  "ownerMarketing.cta": "د اقدام تڼۍ",
  "ownerMarketing.cta.NONE": "بې له تڼۍ",
  "ownerMarketing.cta.VENUE": "میدان پرانیزئ",
  "ownerMarketing.cta.PROMOTION": "تخفیف پرانیزئ",
  "ownerMarketing.choosePromotion": "فعال تخفیف وټاکئ",
  "ownerMarketing.noActivePromotions": "د نښلولو لپاره فعال تخفیف نشته.",
  "ownerMarketing.notifyFollowersPost": "تعقیبوونکي د دې پوسټ په اړه خبر کړئ",
  "ownerMarketing.publishPost": "پوسټ خپور کړئ",
  "ownerMarketing.invalidPostCta": "د دې تڼۍ لپاره معتبر فعال تخفیف وټاکئ.",
  "ownerMarketing.createPostError": "د میدان پوسټ خپور نه شو.",
  "role.PLAYER": "لوبغاړی",
  "role.TEAM_MANAGER": "د ټیم مدیر",
  "role.REFEREE": "ریفري",
  "role.VENUE_STAFF": "د میدان کارکوونکی",
  "role.COMPETITION_ADMIN": "د سیالۍ مدیر",
  "role.VENUE_OWNER": "د میدان مالک",
  "role.PLATFORM_ADMIN": "د پلاتفورم مدیر"
} satisfies Record<TranslationKey, string>;

const resources: Record<LanguageCode, Record<TranslationKey, string>> = { "fa-AF": fa, "ps-AF": ps, en };

export function isRtlLanguage(language: LanguageCode): boolean {
  return language === "fa-AF" || language === "ps-AF";
}

export function translate(language: LanguageCode, key: TranslationKey, params?: Record<string, string | number>): string {
  let value: string = resources[language][key] ?? en[key];
  if (!params) return value;
  for (const [name, replacement] of Object.entries(params)) {
    value = value.replaceAll(`{${name}}`, String(replacement));
  }
  return value;
}

export function getLanguage(language: LanguageCode) {
  return languages.find((item) => item.code === language) ?? languages[0];
}
