-- Private Team Manager workspace. All writes require an active Team Manager subscription.
CREATE TABLE "team_guest_players" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "team_id" uuid NOT NULL REFERENCES "teams"("id") ON DELETE CASCADE, "name" varchar(100) NOT NULL, "position" "player_position" NOT NULL DEFAULT 'UNSPECIFIED', "shirt_number" integer, "created_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "team_guest_jersey_check" CHECK ("shirt_number" IS NULL OR ("shirt_number" BETWEEN 1 AND 99)));
CREATE INDEX "team_guest_players_team_idx" ON "team_guest_players" ("team_id");
CREATE TABLE "team_activities" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "team_id" uuid NOT NULL REFERENCES "teams"("id") ON DELETE CASCADE, "kind" varchar(20) NOT NULL, "title" varchar(120) NOT NULL, "description" text, "place" varchar(160), "starts_at" timestamptz NOT NULL, "ends_at" timestamptz NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "team_activity_dates_check" CHECK ("ends_at" > "starts_at"), CONSTRAINT "team_activity_kind_check" CHECK ("kind" IN ('TRAINING','MEETING','FRIENDLY','OTHER')));
CREATE INDEX "team_activities_team_date_idx" ON "team_activities" ("team_id","starts_at");
CREATE TABLE "team_activity_responses" ("activity_id" uuid NOT NULL REFERENCES "team_activities"("id") ON DELETE CASCADE, "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE, "status" varchar(12) NOT NULL CHECK ("status" IN ('AVAILABLE','UNAVAILABLE','UNSURE')), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("activity_id","user_id"));
CREATE TABLE "team_match_lineups" ("match_id" uuid NOT NULL REFERENCES "competition_matches"("id") ON DELETE CASCADE, "team_id" uuid NOT NULL REFERENCES "teams"("id") ON DELETE CASCADE, "starting_user_ids" jsonb NOT NULL DEFAULT '[]'::jsonb, "substitute_user_ids" jsonb NOT NULL DEFAULT '[]'::jsonb, "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("match_id","team_id"));
CREATE TABLE "team_friendly_challenges" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "from_team_id" uuid NOT NULL REFERENCES "teams"("id") ON DELETE CASCADE, "to_team_id" uuid NOT NULL REFERENCES "teams"("id") ON DELETE CASCADE, "proposed_at" timestamptz NOT NULL, "place" varchar(160), "status" varchar(12) NOT NULL DEFAULT 'PENDING' CHECK ("status" IN ('PENDING','ACCEPTED','DECLINED','CANCELLED')), "created_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "team_challenge_distinct_teams" CHECK ("from_team_id" <> "to_team_id"));
CREATE INDEX "team_friendly_from_idx" ON "team_friendly_challenges" ("from_team_id");
CREATE INDEX "team_friendly_to_idx" ON "team_friendly_challenges" ("to_team_id");
